### ISSUE TITLE
npm run build:sit 出错

### ISSUE THREAD

**Issue by chinahuarvin** [PanJiaChen/vue-element-admin#1010]
building for sit environment...

⠋ building for sit environment...(node:8148) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Cyclic dependency
(node:8148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠴ building for sit environment...

**Comment by PanJiaChen** [comment]
请确定一下你的nonde版本

**Comment by chinahuarvin** [comment]
node v8.9.4     
npm v6.0.1

**Comment by chinahuarvin** [comment]
把node升级到10.9.0 了，如下错误
 arvin@hxd  /www/vue-element-admin   master ●  npm run build:sit

> vue-element-admin@3.8.1 build:sit /www/vue-element-admin
> cross-env NODE_ENV=production env_config=sit node build/build.js

⠋ building for sit environment...(node:10997) UnhandledPromiseRejectionWarning: Error: Cyclic dependency
    at visit (/www/vue-element-admin/node_modules/toposort/index.js:35:13)
    at visit (/www/vue-element-admin/node_modules/toposort/index.js:53:9)
    at visit (/www/vue-element-admin/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/www/vue-element-admin/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/www/vue-element-admin/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/www/vue-element-admin/node_modules/html-webpack-plugin/index.js:364:35)
    at /www/vue-element-admin/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/www/vue-element-admin/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/www/vue-element-admin/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.emitAssets (/www/vue-element-admin/node_modules/webpack/lib/Compiler.js:364:19)
    at onCompiled (/www/vue-element-admin/node_modules/webpack/lib/Compiler.js:231:9)
    at hooks.afterCompile.callAsync.err (/www/vue-element-admin/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/www/vue-element-admin/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/www/vue-element-admin/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/www/vue-element-admin/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/www/vue-element-admin/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
(node:10997) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:10997) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by PanJiaChen** [comment]
`html-webpack-plugin` 你装的不是`^4.0.0-alpha`版本吧

**Comment by chinahuarvin** [comment]
npm  install  的时候提示
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN script-ext-html-webpack-plugin@2.0.1 requires a peer of html-webpack-plugin@^3.0.0 but none is installed. You must install peer dependencies yourself.

然后我
npm install html-webpack-plugin@^3.0.0
+ html-webpack-plugin@3.2.0
added 2 packages from 2 contributors, removed 1 package, updated 1 package and audited 14940 packages in 15.347s
found 0 vulnerabilities

**Comment by chinahuarvin** [comment]
装不上，不知道为什么
npm install html-webpack-plugin@^4.0.0-alpha
npm WARN script-ext-html-webpack-plugin@2.0.1 requires a peer of html-webpack-plugin@^3.0.0 but none is installed. You must install peer dependencies yourself.

+ html-webpack-plugin@4.0.0-alpha
updated 1 package and audited 14939 packages in 30.931s
found 0 vulnerabilities

**Comment by PanJiaChen** [comment]
WARN 可以无视。

**Comment by chinahuarvin** [comment]
ok了，不管install的
`npm WARN script-ext-html-webpack-plugin@2.0.1 requires a peer of html-webpack-plugin@^3.0.0 but none is installed. You must install peer dependencies yourself.`

build 就可以过

**Comment by barray888** [comment]
Yeah  it works . I tried this command "npm install html-webpack-plugin@^4.0.0-alpha" and then build

**Comment by wakaryry** [comment]
Unhandled promise rejections are deprecated. 我一直卡住不动了。一晚上都是在building。是不是在install的时候不需要解决掉那个warn。
> npm WARN script-ext-html-webpack-plugin@2.0.1 requires a peer of html-webpack-plugin@^3.0.0 but none is installed. You must install peer dependencies yourself.

或者：`npm install html-webpack-plugin@^4.0.0-alpha` ?

**Comment by PandaTsui** [comment]
node8.9，我也遇到了一样的问题，一直的build ... 没有任何反应，请问有人解决了吗

**Comment by wakaryry** [comment]
我的很久以前就解决掉了。按照正常流程clone下来，然后install就行。忽视掉所有的警告信息。可以build。我当时build不成功，好像是我把警告信息解决掉了，装了一些warning里面的库。
