### ISSUE TITLE
 Cyclic dependency

### ISSUE THREAD

**Issue by 15036900300** [PanJiaChen/vue-element-admin#1178]
进行npm run build:prod构建的时候报了异常

> building for prod environment...(node:4177) UnhandledPromiseRejectionWarning: Error: Cyclic dependency
    at visit (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/toposort/index.js:35:13)
    at visit (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/toposort/index.js:53:9)
    at visit (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/html-webpack-plugin/index.js:364:35)
    at /Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.emitAssets (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:364:19)
    at onCompiled (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:231:9)
    at hooks.afterCompile.callAsync.err (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
(node:4177) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4177) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠦ building for prod environment...

希望大神给看一下

**Comment by PanJiaChen** [comment]
`html-webpack-plugin`的问题。

`"html-webpack-plugin": "4.0.0-alpha"`
固定死`4.0.0-alpha`版本。

**Comment by 15036900300** [comment]
@PanJiaChen 我将版本修改了，又是另一种错误了

> > vue-element-admin@3.8.1 build:prod /Users/litairan/work/ideaProjects/github/vue-element-admin
> cross-env NODE_ENV=production env_config=prod node build/build.js

⠋ building for prod environment.../Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/script-ext-html-webpack-plugin/lib/plugin.js:50
      compilation.hooks.htmlWebpackPluginAlterAssetTags.tap(PLUGIN, alterAssetTags);
                                                        ^

TypeError: Cannot read property 'tap' of undefined
    at ScriptExtHtmlWebpackPlugin.compilationCallback (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/script-ext-html-webpack-plugin/lib/plugin.js:50:57)
    at SyncHook.eval [as call] (eval at create (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/webpack/lib/Compiler.js:504:26)
    at hooks.beforeCompile.callAsync.err (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/webpack/lib/Compiler.js:540:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/webpack/lib/Compiler.js:535:28)
    at readRecords.err (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/webpack/lib/Compiler.js:274:11)
    at Compiler.readRecords (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/webpack/lib/Compiler.js:402:11)
    at hooks.run.callAsync.err (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/webpack/lib/Compiler.js:271:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/webpack/lib/Compiler.js:268:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/litairan/work/ideaProjects/github/vue-element-admin/node_modules/tapable/lib/Hook.js:154:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@3.8.1 build:prod: `cross-env NODE_ENV=production env_config=prod node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-element-admin@3.8.1 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by 15036900300** [comment]
@PanJiaChen 我更改了版本，又是另一种异常

> TypeError: Cannot read property 'tap' of undefined
    at ScriptExtHtmlWebpackPlugin.compilationCallback (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/script-ext-html-webpack-plugin/lib/plugin.js:50:57)
    at SyncHook.eval [as call] (eval at create (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:11:1)
    at SyncHook.lazyCompileHook [as _call] (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:504:26)
    at hooks.beforeCompile.callAsync.err (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:540:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:535:28)
    at readRecords.err (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:274:11)
    at Compiler.readRecords (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:402:11)
    at hooks.run.callAsync.err (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:271:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/webpack/lib/Compiler.js:268:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/litairan/work/ideaProjects/gitlab/nemdp-element/node_modules/tapable/lib/Hook.js:35:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@3.8.1 build:prod: `cross-env NODE_ENV=production env_config=prod node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-element-admin@3.8.1 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by PanJiaChen** [comment]
你确定是`4.0.0-alpha`版本么。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1049

**Comment by 15036900300** [comment]
方便qq交流吗大佬，或者微信都行

**Comment by 15036900300** [comment]
指定"html-webpack-plugin": "4.0.0-alpha"这个版本不是只是修改package.json文件就可以了吗 @PanJiaChen

**Comment by 15036900300** [comment]
进行npm install，有这个警告

> npm WARN script-ext-html-webpack-plugin@2.0.1 requires a peer of html-webpack-plugin@^3.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by 15036900300** [comment]
按照你的那个操作了，但是还是报错

**Comment by PanJiaChen** [comment]
warning 无视就可以了

**Comment by 15036900300** [comment]
我按照你发的那个从新install了一下，还是报错

**Comment by 15036900300** [comment]
> new HtmlWebpackPlugin({
      filename: config.build.index,
      template: 'index.html',
      inject: true,
      favicon: resolve('favicon.ico'),
      title: 'vue-element-admin',
      path: config.build.assetsPublicPath + config.build.assetsSubDirectory,
      chunkSortMode: 'none',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
        // more options:
        // https://github.com/kangax/html-minifier#options-quick-reference
      }
      // default sort mode uses toposort which cannot handle cyclic deps
      // in certain cases, and in webpack 4, chunk order in HTML doesn't
      // matter anyway
    })

我这样修改可以吗？添加了

> chunkSortMode: 'none'

**Comment by wql77** [comment]
@15036900300 "html-webpack-plugin": "4.0.0-alpha"，改成这样之后，还是报错，这个问题你解决了吗，求分享
