### ISSUE TITLE
npm run build:prod时postcss插件报错

### ISSUE THREAD

**Issue by flzyup** [PanJiaChen/vue-element-admin#1242]
RT，看了下插件的源码没太看明白，postcss-merge-longhand这个插件在执行的时候报错了
dev情况下正常，应该是插件处理css的时候报错了

(node:68297) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'search' of undefined
    at /Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/static/css/chunk-66f9.814cd1f3.css:1:371546
    at isValueCustomProp (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:106:45)
    at /Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:449:18
    at mergeRules (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss-merge-longhand/dist/lib/mergeRules.js:46:17)
    at wsc.forEach (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:438:34)
    at Array.forEach (<anonymous>)
    at Object.merge (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:436:9)
    at _decl2.default.forEach.p (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss-merge-longhand/dist/index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss-merge-longhand/dist/index.js:20:28)
    at /Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss/lib/container.js:239:18
    at /Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss/lib/container.js:135:18
    at Root.each (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss/lib/container.js:237:19)
    at css (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/postcss-merge-longhand/dist/index.js:19:13)
    at initializePlugin (/Users/yonnielu/Documents/sourcecode/wefirst/wefirst-admin/node_modules/cssnano/dist/index.js:35:51)
(node:68297) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:68297) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by flzyup** [comment]
https://github.com/cssnano/cssnano/releases 作者已经发布新版本了cssnano了 麻烦能更新下不？
