### ISSUE TITLE
打包时报错，说promise没有catch到异常，这个情况该怎么办呀？

### ISSUE THREAD

**Issue by luoshiwei** [PanJiaChen/vue-element-admin#1253]
`(node:1019) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'search' of undefined
    at /Users/home/projects/vue-admin-template/static/css/app.ede15ce0.css:37076:1
    at isValueCustomProp (/Users/home/projects/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:106:45)
    at /Users/home/projects/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:449:18
    at mergeRules (/Users/home/projects/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/mergeRules.js:46:17)
    at wsc.forEach (/Users/home/projects/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:438:34)
    at Array.forEach (<anonymous>)
    at Object.merge (/Users/home/projects/vue-admin-template/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:436:9)
    at _decl2.default.forEach.p (/Users/home/projects/vue-admin-template/node_modules/postcss-merge-longhand/dist/index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (/Users/home/projects/vue-admin-template/node_modules/postcss-merge-longhand/dist/index.js:20:28)
    at /Users/home/projects/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:239:18
    at /Users/home/projects/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:135:18
    at Root.each (/Users/home/projects/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/home/projects/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (/Users/home/projects/vue-admin-template/node_modules/cssnano/node_modules/postcss/lib/container.js:237:19)
    at css (/Users/home/projects/vue-admin-template/node_modules/postcss-merge-longhand/dist/index.js:19:13)
    at initializePlugin (/Users/home/projects/vue-admin-template/node_modules/cssnano/dist/index.js:35:51)
(node:1019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This errororiginated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1222

你现在只需要

删除 node_modules文件夹 和 package-lock.json
然后
```bash
npm cache clean --force
npm install --registry=https://registry.npm.taobao.org
```

**Comment by roc2539** [comment]
> #1222
> 
> 你现在只需要
> 
> 删除 node_modules文件夹 和 package-lock.json
> 然后
> 
> ```shell
> npm cache clean --force
> npm install --registry=https://registry.npm.taobao.org
> ```

@PanJiaChen 还需要其他修改吗？或是要更新什么版本？

**Comment by roc2539** [comment]
@PanJiaChen 搞定了，还要看下 #1178
