### ISSUE TITLE
运行npm run build:prod报错

### ISSUE THREAD

**Issue by busyboy-ws** [PanJiaChen/vue-element-admin#1275]
程序在打包时，运行生产环境配置时出现报错。
`$ npm run build:prod

> vue-element-admin@3.9.1 build:prod E:\web\vue-admin
> cross-env NODE_ENV=production env_config=prod node build/build.js

- building for prod environment...
(node:10744) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'search' of undefined
    at E:\web\vue-admin\static\css\chunk-210d.cb0d22c4.css:1:371546
    at isValueCustomProp (E:\web\vue-admin\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:106:45)
    at E:\web\vue-admin\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:449:18
    at mergeRules (E:\web\vue-admin\node_modules\postcss-merge-longhand\dist\lib\mergeRules.js:46:17)
    at wsc.forEach (E:\web\vue-admin\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:438:34)
    at Array.forEach (<anonymous>)
    at Object.merge (E:\web\vue-admin\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:436:9)
    at _decl2.default.forEach.p (E:\web\vue-admin\node_modules\postcss-merge-longhand\dist\index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (E:\web\vue-admin\node_modules\postcss-merge-longhand\dist\index.js:20:28)
    at E:\web\vue-admin\node_modules\cssnano\node_modules\postcss\lib\container.js:239:18
    at E:\web\vue-admin\node_modules\cssnano\node_modules\postcss\lib\container.js:135:18
    at Root.each (E:\web\vue-admin\node_modules\cssnano\node_modules\postcss\lib\container.js:101:16)
    at Root.walk (E:\web\vue-admin\node_modules\cssnano\node_modules\postcss\lib\container.js:131:17)
    at Root.walkRules (E:\web\vue-admin\node_modules\cssnano\node_modules\postcss\lib\container.js:237:19)
    at css (E:\web\vue-admin\node_modules\postcss-merge-longhand\dist\index.js:19:13)
    at initializePlugin (E:\web\vue-admin\node_modules\cssnano\dist\index.js:35:51)
(node:10744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:10744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1253
