### ISSUE TITLE
webpack.NoEmitOnErrorsPlugin is not a constructor 执行npm run build:prod报这个错误

### ISSUE THREAD

**Issue by junge68** [PanJiaChen/vue-element-admin#131]

**Comment by PanJiaChen** [comment]
NoEmitOnErrorsPlugin 是webpack2+内置plugin
所以你确定自己webpack版本

**Comment by junge68** [comment]
我升级了webpack,升级到2.5.1,但是还是会报这个错误

**Comment by PanJiaChen** [comment]
https://webpack.js.org/plugins/no-emit-on-errors-plugin/
这是内置的。。。也不用配置 
你能把报错信息贴一下么

**Comment by junge68** [comment]
#`我刚才用了您的build跟packjson.json文件,现在好了,但是会报这个错误`in ./src/App.vue
Module build failed: TypeError: loader.charAt is not a function
    at ensureBang (D:\project\SmartFireControl-UI\node_modules\vue-loader\lib\loader.js:180:16)
    at getLoaderString (D:\project\SmartFireControl-UI\node_modules\vue-loader\lib\loader.js:145:18)
    at getRequireString (D:\project\SmartFireControl-UI\node_modules\vue-loader\lib\loader.js:80:7)
    at getRequire (D:\project\SmartFireControl-UI\node_modules\vue-loader\lib\loader.js:71:7)
    at D:\project\SmartFireControl-UI\node_modules\vue-loader\lib\loader.js:205:11
    at Array.forEach (native)
    at Object.module.exports (D:\project\SmartFireControl-UI\node_modules\vue-loader\lib\loader.js:198:18)
 @ ./src/main.js 23:11-27
 @ multi ./build/dev-client ./src/main.js`
所有的组件都找不到了

**Comment by PanJiaChen** [comment]
所以你确定你的版本号和我一样么。。。你这个就是vue-loader版本号不对啊。。。
