### ISSUE TITLE
tag3.3到tag3.4 安装webpack-dev-server运行出错

### ISSUE THREAD

**Issue by zhangaofei** [PanJiaChen/vue-element-admin#1393]
我看了tag3.3到tag3.4热更新改用webpack-dev-server同时build文件夹不在使用dev-client和dev-server;然后直接在3.4之前版本（webpack使用2.61）进行修改，安装了相应的更改的模块；
packjson也配置了："dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",但是运行后报错
> juicy@1.0.2 dev E:\ele_all\ele_1.0.2\vue-element-admin-1.0.2\vue-element-admin-1.0.2
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

E:\ele_all\ele_1.0.2\vue-element-admin-1.0.2\vue-element-admin-1.0.2\node_modules\ajv-keywords\keywords\instanceof.js:52
    throw new Error('invalid "instanceof" keyword value ' + c);
    ^

Error: invalid "instanceof" keyword value Promise
    at getConstructor (E:\ele_all\ele_1.0.2\vue-element-admin-1.0.2\vue-element-admin-1.0.2\node_modules\ajv-keywords\keywords\instanceof.js:52:11)
    at Ajv.compile (E:\ele_all\ele_1.0.2\vue-element-admin-1.0.2\vue-element-admin-1.0.2\node_modules\ajv-keywords\keywords\instanceof.js:21:27)
    at Object.useCustomRule (E:\ele_all\ele_1.0.2\vue-element-admin-1.0.2\vue-element-admin-1.0.2\node_modules\ajv\lib\compile\index.js:289:26)
    at Object.generate_custom [as code] (E:\ele_all\ele_1.0.2\vue-element-admin-1.0.2\vue-element-admin-1.0.2\node_modules\ajv\lib\dotjs\custom.js:31:24)
    at Object.generate_validate [as validate] (E:\ele_all\ele_1.0.2\vue-element-admin-1.0.2\vue-element-admin-1.0.2\node_modules\ajv\lib\dotjs\validate.js:228:37)
    at Object.generate_anyOf [as code] (E:\ele_all\ele_1.0.2\vue-element-admin-1.0.2\vue-element-admin-1.0.2\node_modules\ajv\lib\dotjs\anyOf.js:34:27)；
群主能给点指导意见吗

**Comment by PanJiaChen** [comment]
这版本都要一年前了。。。

https://github.com/webpack/webpack-dev-server/issues/1355

你的问题好像更新版本就可以了。
