### ISSUE TITLE
debian执行run dev 报错

### ISSUE THREAD

**Issue by DaweiZhao007** [PanJiaChen/vue-element-admin#1429]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.5.0
3 info using node@v10.14.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-element-admin@3.9.3~predev: vue-element-admin@3.9.3
6 info lifecycle vue-element-admin@3.9.3~dev: vue-element-admin@3.9.3
7 verbose lifecycle vue-element-admin@3.9.3~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-element-admin@3.9.3~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dwzhao/vue-element-admin/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle vue-element-admin@3.9.3~dev: CWD: /home/dwzhao/vue-element-admin
10 silly lifecycle vue-element-admin@3.9.3~dev: Args: [ '-c',
10 silly lifecycle   'cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js' ]
11 silly lifecycle vue-element-admin@3.9.3~dev: Returned: code: 1  signal: null
12 info lifecycle vue-element-admin@3.9.3~dev: Failed to exec dev script
13 verbose stack Error: vue-element-admin@3.9.3 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid vue-element-admin@3.9.3
15 verbose cwd /home/dwzhao/vue-element-admin
16 verbose Linux 3.16.0-4-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v10.14.2
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-element-admin@3.9.3 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
22 error Exit status 1
23 error Failed at the vue-element-admin@3.9.3 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
首次执行启动时报错

**Comment by PanJiaChen** [comment]
请确定以正确安装所以依赖。

**Comment by energygreek** [comment]
问题解决了吗？ 我也遇到这个问题
