### ISSUE TITLE
edge 导航条bug按钮显示的错误内容

### ISSUE THREAD

**Issue by dielangsea** [PanJiaChen/vue-element-admin#1553]
TypeError: Unable to get property 'parent' of undefined or null reference at Anonymous function (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:45:2184) at v (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:45:2006) at u (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:45:12288) at a (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:45:11683) at Rt.prototype.match (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:45:22404) at Rt.prototype.resolve (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:45:23746) at C.render (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:45:3334) at t.prototype._render (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:18:32687) at Anonymous function (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:18:60889) at Me.prototype.get (http://39.104.230.41/static/js/chunk-libs.4cc50704.js:18:15976)

**Comment by ajiu9** [comment]
请问这个问题是怎么解决的
