### ISSUE TITLE
本地启动报错loader-runner

### ISSUE THREAD

**Issue by cncert** [PanJiaChen/vue-element-admin#1639]
$ npm run dev

> vue-element-admin@3.10.0 dev J:\pro\vue-element-admin
> cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'loader-runner'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (J:\pro\vue-element-admin\node_modules\_webpack@4.16.5@webpack\lib\NormalModule.js:16:36)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@3.10.0 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@3.10.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\wt\AppData\Roaming\npm-cache\_logs\2019-02-25T15_39_38_792Z-debug.log

**Comment by PanJiaChen** [comment]
* delete node_modules
* delete package-lock.json
* npm cache clean --force
* npm install
