### ISSUE TITLE
本地构建失败，npm和node要求什么版本？

### ISSUE THREAD

**Issue by saillen** [PanJiaChen/vue-element-admin#1669]
项目clone后，`npm install`、`npm run dev` 报如下错误：

- nodeJs版本：v11.10.1
- npm版本：6.7.0
- webpack版本：4.29.6

```

> vue-element-admin@3.10.0 dev /Users/saillen/WorkSpace/node-project/vue-element-admin
> cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 10% building modules 1/1 modules 0 activeevents.js:173                       i       throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1440:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@3.10.0 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@3.10.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/saillen/.npm/_logs/2019-03-06T12_16_14_803Z-debug.log
```

**Comment by PanJiaChen** [comment]
请先自己搜索一下问题。

比如：https://segmentfault.com/a/1190000015274463

**Comment by saillen** [comment]
THK，很少搞Node，`run`了几次报错都不一样，把Node和NPM全部删除重装好了，看来我饶远路了。😓
