### ISSUE TITLE
现在我用的vueCli3 和 webpack4 参考这个项目搭建后台管理

### ISSUE THREAD

**Issue by summer1874** [PanJiaChen/vue-element-admin#1755]
请问下我应该是参考master上的，还是参考branch v4.0的去搭建？（刚刚拉了下v4.0，好像部分功能还不太完善），大佬准备什么时候发布v4.0。 :tada: :tada: :tada:

**Comment by PanJiaChen** [comment]
4.0分支其实我个人觉得没太大问了吧，

比如有哪些不完善的地方？

**Comment by summer1874** [comment]
![admin](https://user-images.githubusercontent.com/21187224/54799473-5f5a3c80-4c98-11e9-8e4b-616e4f1be3b9.gif)

响应式还没完善（如图）

**Comment by PanJiaChen** [comment]
感谢反馈，我修复了一下。

我建议可以用4.0分支了，因为没意外的话，我下周就准备发布beta版本了，之后测试一段时间之后，下个月会发布正式版本和相关教程和文章。

如果遇到任何问题都可以反馈。

**Comment by summer1874** [comment]
谢谢大佬即时的指导~

**Comment by summer1874** [comment]
**branch v4.0 在执行 ` yarn run build:prod`时报错**

- 错误信息
```
 ERROR  Error loading vue.config.js:
 ERROR  SyntaxError: Unexpected token export
C:\Users\86152\Desktop\vue-admin\vue-element-admin\src\settings.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Module._compile (C:\Users\86152\Desktop\vue-admin\vue-element-admin\node_modules\pirates\lib\index.js:99:2
4)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (C:\Users\86152\Desktop\vue-admin\vue-element-admin\node_modules\pirates\lib\ind
ex.js:104:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**branch v4.0 在执行 ` yarn run dev`会有如下警告**
- 警告
```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assu
me version 2.x when no version is passed. Since this default version will likely change in future versions of Bab
el, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `p
ackage.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3
```
执行`yarn add core-js@2 `后依旧会有此警告信息

**Comment by PanJiaChen** [comment]
@summer1874  错误修复了。

`WARNING` 那个不太好改，我周末思考一下。

**Comment by zhychao** [comment]
v4.0版本什么时候正式发布啊？我现在能用这个beta版本直接开发吗？

**Comment by PanJiaChen** [comment]
@zhychao 可以

**Comment by imsole** [comment]
> @summer1874 错误修复了。
> 
> `WARNING` 是一个上游的错误，和我的配置关系不大。

请问你是怎么修复的

**Comment by PanJiaChen** [comment]
升级一下 vue-cli 就可以了。
现在 4.0分支已经没这个问题了。 @imsole

**Comment by imsole** [comment]
OK

**Comment by zhychao** [comment]
this.$store.dispatch('user/login', this.loginForm)  这个.dispatch('user/login'）为什么是这样写的？

**Comment by neohan666** [comment]
> this.$store.dispatch('user/login', this.loginForm) 这个.dispatch('user/login'）为什么是这样写的？

https://vuex.vuejs.org/zh/guide/modules.html 这是vuex的命名空间写法

**Comment by jaysunxiao** [comment]
很期待vue4.0，简化了很多配置

**Comment by PanJiaChen** [comment]
正式版已发布。
