### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by hyahm** [PanJiaChen/vue-element-admin#1952]
## Question（提问）

系统： centos 7.2
node : 10.15.3

[root@hyahm vue]# npm run build:prod

> vue-element-admin@3.8.0 build:prod /source/ITflow/vue
> cross-env NODE_ENV=production env_config=prod node build/build.js

⠦ building for prod environment...(node:1313) UnhandledPromiseRejectionWarning: Error: Cyclic dependency
    at visit (/source/ITflow/vue/node_modules/toposort/index.js:35:13)
    at visit (/source/ITflow/vue/node_modules/toposort/index.js:53:9)
    at visit (/source/ITflow/vue/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/source/ITflow/vue/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/source/ITflow/vue/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/source/ITflow/vue/node_modules/html-webpack-plugin/index.js:364:35)
    at /source/ITflow/vue/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/source/ITflow/vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:41:1)
    at AsyncSeriesHook.lazyCompileHook (/source/ITflow/vue/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/source/ITflow/vue/node_modules/webpack/lib/Compiler.js:364:19)
    at onCompiled (/source/ITflow/vue/node_modules/webpack/lib/Compiler.js:231:9)
    at hooks.afterCompile.callAsync.err (/source/ITflow/vue/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/source/ITflow/vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/source/ITflow/vue/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/source/ITflow/vue/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/source/ITflow/vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
(node:1313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vue-cli/issues/1669
