### ISSUE TITLE
无法build:prod。。报错：caniuse-lite is outdated 

### ISSUE THREAD

**Issue by Thomastar** [PanJiaChen/vue-element-admin#1961]
$ npm run build:prod

> vue-element-admin@3.9.3 build:prod E:\project\tb_admin
> cross-env NODE_ENV=production env_config=prod node build/build.js

- building for prod environment...
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
(node:10540) UnhandledPromiseRejectionWarning: BrowserslistError: Unknown browser kaios
    at checkName (E:\project\tb_admin\node_modules\caniuse-api\node_modules\browserslist\index.js:124:20)
    at Function.select (E:\project\tb_admin\node_modules\caniuse-api\node_modules\browserslist\index.js:731:18)
    at E:\project\tb_admin\node_modules\caniuse-api\node_modules\browserslist\index.js:155:33
    at Array.reduce (<anonymous>)
    at resolve (E:\project\tb_admin\node_modules\caniuse-api\node_modules\browserslist\index.js:136:18)
    at browserslist (E:\project\tb_admin\node_modules\caniuse-api\node_modules\browserslist\index.js:233:16)
    at isSupported (E:\project\tb_admin\node_modules\caniuse-api\dist\index.js:62:37)
    at E:\project\tb_admin\node_modules\cssnano\node_modules\postcss-reduce-initial\dist\index.js:40:60
    at initializePlugin (E:\project\tb_admin\node_modules\cssnano\dist\index.js:31:51)
    at <anonymous>
(node:10540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Thomastar** [comment]
npm update caniuse-lite browserslist  没有任何效果

**Comment by PanJiaChen** [comment]
https://github.com/postcss/autoprefixer/issues/1184

**Comment by JckYabo** [comment]
直接update可能不行，我是直接删掉了 node_modules文件夹下的caniuse-lite 和 browserslist两个文件夹，然后重新 npm install就可以了。
