### ISSUE TITLE
请问 有人启动项目遇到这种情况么？在线等 

### ISSUE THREAD

**Issue by miya201207** [PanJiaChen/vue-element-admin#2265]
D:\vue-element-admin-master>node -v
v8.12.0

D:\vue-element-admin-master>npm install
npm WARN deprecated runjs@4.4.2: This project has been renamed to 'tasksfile'. Install using 'npm install tasksfile' instead.
npm WARN deprecated microcli@1.3.3: This project has been renamed to @pawelgalazka/cli . Install using @pawelgalazka/cli instead
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated microargs@1.1.2: This project has been renamed to @pawelgalazka/cli-args. Install using @pawelgalazka/cli-args instead
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Error while executing:
npm ERR! C:\Program Files (x86)\Git\cmd\git.EXE ls-remote -h -t https://github.com/nhn/raphael.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/nhn/raphael.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol versionnpm ERR!
npm ERR! exited with error code: 128

**Comment by mysllove** [comment]
npm cache clean --force.(祝你好运！) 然后重复执行

**Comment by 13476075014** [comment]
我也遇到这个问题了，解决了吗？

**Comment by liuxiaodeng** [comment]
我也遇到了这个，请问解决了吗

**Comment by GitACDreamer** [comment]
设置淘宝源试下用cnpm install 也许就可以了

**Comment by xjx0106** [comment]
我也遇到了同樣的問題，當項目在jenkins部署的時候，報錯如下，還沒找到解決辦法：

npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 35504ms
npm verb stack Error: exited with error code: 128
npm verb stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
npm verb stack     at ChildProcess.emit (events.js:198:13)
npm verb stack     at maybeClose (internal/child_process.js:982:16)
npm verb stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
npm verb stack     at Socket.emit (events.js:198:13)
npm verb stack     at Pipe._handle.close (net.js:606:12)
npm verb cwd /var/lib/jenkins/workspace/maya-front-dev-integration
npm verb Linux 3.10.0-693.el7.x86_64
npm verb argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "--verbose"
npm verb node v10.16.0
npm verb npm  v6.9.0
npm ERR! Error while executing:
npm ERR! /bin/git ls-remote -h -t https://github.com/nhn/raphael.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/nhn/raphael.git/': Network file descriptor is not connected
npm ERR! 
npm ERR! exited with error code: 128
npm verb exit [ 1, true ]
npm timing npm Completed in 36671ms

**Comment by Lonor** [comment]
非常明显，国内网络原因，GitHub 访问收到了限制。有人知道这个 git ls-remote 是在哪个依赖里的吗？

**Comment by zepc007** [comment]
# 开梯子打开全局梯子npm下就可以了

**Comment by Leocat81** [comment]
**刚好碰到这个问题，我这边是因为服务器连接github速度很慢，导致下载这个包超时， 检查了下是"tui-editor"这个库的依赖，如果你们项目中没有用到那个markdown组件，可以把这个从package.json中移除**
https://github.com/PanJiaChen/vue-element-admin/issues/3491#issuecomment-800168161

**Comment by junfugao8** [comment]
挂全局梯子，在webstorm跑就得了，挂梯子在cmd跑还是错。

**Comment by wswind** [comment]
> 我也遇到了同樣的問題，當項目在jenkins部署的時候，報錯如下，還沒找到解決辦法：
> 
> npm timing stage:rollbackFailedOptional Completed in 1ms
> npm timing stage:runTopLevelLifecycles Completed in 35504ms
> npm verb stack Error: exited with error code: 128
> npm verb stack at ChildProcess. (/usr/local/node/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
> npm verb stack at ChildProcess.emit (events.js:198:13)
> npm verb stack at maybeClose (internal/child_process.js:982:16)
> npm verb stack at Socket.stream.socket.on (internal/child_process.js:389:11)
> npm verb stack at Socket.emit (events.js:198:13)
> npm verb stack at Pipe._handle.close (net.js:606:12)
> npm verb cwd /var/lib/jenkins/workspace/maya-front-dev-integration
> npm verb Linux 3.10.0-693.el7.x86_64
> npm verb argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "--verbose"
> npm verb node v10.16.0
> npm verb npm v6.9.0
> npm ERR! Error while executing:
> npm ERR! /bin/git ls-remote -h -t https://github.com/nhn/raphael.git
> npm ERR!
> npm ERR! fatal: unable to access 'https://github.com/nhn/raphael.git/': Network file descriptor is not connected
> npm ERR!
> npm ERR! exited with error code: 128
> npm verb exit [ 1, true ]
> npm timing npm Completed in 36671ms

一样的问题，本地能编过，放到jenkins上就报错，使用node:12的镜像

**Comment by wswind** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/3491

**Comment by martinageradams** [comment]
@miya201207 Please close this issue #3419

**Comment by GitACDreamer** [comment]
先删除`node_modules` ,再使用淘宝镜像 ，运行`cnpm install `
