### ISSUE TITLE
启动时转义符报错

### ISSUE THREAD

**Issue by cuicc1991** [PanJiaChen/vue-element-admin#2300]
更新下代码后执行 npm install后 运行npm run dev
 然后使用转移符的地方报错，网上试过了增加bable配置还是不行，请问该怎么解决？

PS E:\vue\vue-element-admin-master> npm run dev

> vue-element-admin@4.2.1 dev E:\vue\vue-element-admin-master
> vue-cli-service serve

E:\vue\vue-element-admin-master\node_modules\open\index.js:24
                ...options
                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\vue\vue-element-admin-master\node_modules\@vue\cli-shared-utils\lib\openBrowser.js:9:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@4.2.1 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@4.2.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ccc\AppData\Roaming\npm-cache\_logs\2019-06-28T07_26_20_615Z-debug.log
PS E:\vue\vue-element-admin-master> npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
PS E:\vue\vue-element-admin-master>
PS E:\vue\vue-element-admin-master>
PS E:\vue\vue-element-admin-master> npm run dev

> vue-element-admin@4.2.1 dev E:\vue\vue-element-admin-master
> vue-cli-service serve

E:\vue\vue-element-admin-master\node_modules\open\index.js:24
                ...options
                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\vue\vue-element-admin-master\node_modules\@vue\cli-shared-utils\lib\openBrowser.js:9:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@4.2.1 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@4.2.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ccc\AppData\Roaming\npm-cache\_logs\2019-06-28T07_28_11_189Z-debug.log

**Comment by PanJiaChen** [comment]
babel 没配对。
