### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by whq920729** [PanJiaChen/vue-element-admin#2308]
## Question（提问）
npm WARN deprecated runjs@4.4.2: This project has been renamed to 'tasksfile'. Install using 'npm install tasksfile' instead.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/sohee-lee7/Squire.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by hedekun** [comment]
依赖没有安装好。npm install一下或者把node_modules删除重新npm install

**Comment by 281831964** [comment]
4404 verbose stack Error: exited with error code: 128
4404 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\finished.js:12:19)
4404 verbose stack     at ChildProcess.emit (events.js:189:13)
4404 verbose stack     at maybeClose (internal/child_process.js:970:16)
4404 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
4405 verbose cwd C:\Users\carigold\Downloads\vue-element-admin-master
4406 verbose Windows_NT 10.0.17134
4407 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
4408 verbose node v10.15.3
4409 verbose npm  v6.4.1
4410 error Error while executing:
4410 error D:\carigold\PortableGit\bin\git.EXE ls-remote -h -t ssh://git@github.com/sohee-lee7/Squire.git
4410 error
4410 error undefined
4410 error exited with error code: 128
4411 verbose exit [ 1, true ]


清除缓存重新npm install 还是不行啊

**Comment by zehongfan** [comment]
同问

**Comment by whq920729** [comment]
please change to '**cnpm install**'......, I have resolved this problem.

**Comment by whq920729** [comment]
please change to 'cnpm install'......, I have resolved this problem.




------------------ 原始邮件 ------------------
发件人: "zehongfan"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 上午10:18
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com>;
抄送: "df+"<455626828@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PanJiaChen/vue-element-admin] 安装错误 (#2308)




同问

**Comment by xdkaka** [comment]
yarn fail +1
````
error An unexpected error occurred: "https://raw.githubusercontent.com/sohee-lee7/Squire/b1e0e1031fa18912d233c204cbe7c7fae4a42621/package.json: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/zyk/Documents/www/zyk/banyu/classroom-review-admin/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
````

**Comment by PanJiaChen** [comment]
try `git config --global url."https://github".insteadOf github:`

**Comment by yijinc** [comment]
同样的问题，在自己电脑上不报错。在服务器上构建报错

**Comment by haroldduan** [comment]
My solution is to reset NPM registry,
`npm config set registry https://registry.npm.taobao.org`
`npm info underscore`
It's successed!
![Selection_323](https://user-images.githubusercontent.com/16353458/82414793-2c812380-9aaa-11ea-8742-5edf3d263464.jpg)
![Selection_324](https://user-images.githubusercontent.com/16353458/82414824-3571f500-9aaa-11ea-9224-b078f0ea0b0c.jpg)
![Selection_325](https://user-images.githubusercontent.com/16353458/82414838-3a36a900-9aaa-11ea-8a6f-1b59fbb893cf.jpg)

**Comment by rogerIF** [comment]
`git config --global url."https://github".insteadOf github:`这个命令不起作用，使用yarn依旧报错，npm可以安装

**Comment by Littleiii** [comment]
在hosts文件加入下面配置就可以了

```
199.232.68.133 raw.githubusercontent.com
```

**Comment by Darkhorse007** [comment]
@Littleiii You must be the top

**Comment by kamner** [comment]
> 在hosts文件加入下面配置就可以了,顶起来
> 
> ```
> 199.232.68.133 raw.githubusercontent.com
> ```

It works!

**Comment by wechangel** [comment]
> try `git config --global url."https://github".insteadOf github:`
> 
> [nhn/tui.editor#433](https://github.com/nhn/tui.editor/issues/433)

公司内网环境下，可以先吧markdown组件相关的删了，其中有package.json tui-editor的配置和markdown的页面。
先过了再说

**Comment by zymbth** [comment]
> 在hosts文件加入下面配置就可以了,顶起来
> 
> ```
> 199.232.68.133 raw.githubusercontent.com
> ```

试过有效，不过dns经常变，用的时候需要查下

**Comment by wangliangyu** [comment]
> 同样的问题，在自己电脑上不报错。在服务器上构建报错

请后后面怎么解决了

**Comment by Corgis** [comment]
先去package.json去除 tui-editor的安装
