### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by qq471251098** [PanJiaChen/vue-element-admin#2311]
#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/43675008/60444322-8f2dbe80-9c4f-11e9-838d-3c5dd5800aa6.png)

#### Link to minimal reproduction（最小可在线还原demo）
无demo

#### Other relevant information（格外信息）
- Your OS: win10系统32位
- Node.js version:node版本10.15.3
- vue-element-admin version:4.2.1

**Comment by qq471251098** [comment]
图片好像挂了，复制下报错代码
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-admin-template@4.2.1 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-admin-template@4.2.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AIERXUAN\AppData\Roaming\npm-cache\_logs\2019-07-01T14_21_58_949Z-debug.log

**Comment by zgsnbtl** [comment]
vue.config.js 中 open:true 注释掉 就可以了

**Comment by zgsnbtl** [comment]
> ## 安装项目依赖之后运行报错（问题描述）
> #### 重现的步骤（问题复现步骤）
> #### 截图或Gif（截图或动态图）
> ![图片](https://user-images.githubusercontent.com/43675008/60444322-8f2dbe80-9c4f-11e9-838d-3c5dd5800aa6.png)
> 
> #### 链接到最小复制（最小可在线还原演示）
> 无演示
> 
> #### 其他相关信息（格外信息）
> * 你的操作系统：win10系统32位
> * Node.js版本：node版本10.15.3
> * vue-element-admin版本：4.2.1

vue.config.js中open：true注释掉就可以了

**Comment by qq471251098** [comment]
谢谢大佬的指点




------------------ 原始邮件 ------------------
发件人: "鲍泽功"<notifications@github.com>;
发送时间: 2019年7月6日(星期六) 晚上8:06
收件人: "PanJiaChen/vue-element-admin"<vue-element-admin@noreply.github.com>;
抄送: "471251098"<471251098@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [PanJiaChen/vue-element-admin] npm run dev 报错 (#2311)



 
安装项目依赖之后运行报错（问题描述）
 
重现的步骤（问题复现步骤）
 
截图或Gif（截图或动态图）
 

 
链接到最小复制（最小可在线还原演示）
 
无演示
 
其他相关信息（格外信息）
  
你的操作系统：win10系统32位
 
Node.js版本：node版本10.15.3
 
vue-element-admin版本：4.2.1
   
vue.config.js中open：true注释掉就可以了

**Comment by YL13598309856** [comment]
> vue.config.js 中 open:true 注释掉 就可以了
为什么啊？你真厉害

**Comment by Stone-wh** [comment]
好奇，为什么注释掉了就可以了？

**Comment by fangYiYuan** [comment]
一样的报错，我的vue.config.js里没有open:true怎么办
