### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by ppatch** [PanJiaChen/vue-element-admin#2349]
#### Steps to reproduce（问题复现步骤）
0. npm cache clean --force
1. rm -rf node_modules && rm package-lock.json && npm install
2. npm run build:sit

#### 报错
```
⠏ building for sit environment...npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@3.10.0 build:sit: `cross-env NODE_ENV=production env_config=sit node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@3.10.0 build:sit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-09T05_45_05_636Z-debug.log
```
##### log
```
0 info it worked if it ends with ok
1 verbose cli [ '/server/node/bin/node',
1 verbose cli   '/server/node/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:sit' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild:sit', 'build:sit', 'postbuild:sit' ]
5 info lifecycle vue-element-admin@3.10.0~prebuild:sit: vue-element-admin@3.10.0
6 info lifecycle vue-element-admin@3.10.0~build:sit: vue-element-admin@3.10.0
7 verbose lifecycle vue-element-admin@3.10.0~build:sit: unsafe-perm in lifecycle true
8 verbose lifecycle vue-element-admin@3.10.0~build:sit: PATH: /server/node/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/www/sun/app/public/admin/node_modules/.bin:/server/node/bin:/usr/local/nginx/sbin:/usr/local/php/bin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/server/jdk1.8.0/bin:/server/maven/bin:/mongodb-3.2.5/bin:/root/bin
9 verbose lifecycle vue-element-admin@3.10.0~build:sit: CWD: /www/sun/app/public/admin
10 silly lifecycle vue-element-admin@3.10.0~build:sit: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production env_config=sit node build/build.js' ]
11 silly lifecycle vue-element-admin@3.10.0~build:sit: Returned: code: 1  signal: null
12 info lifecycle vue-element-admin@3.10.0~build:sit: Failed to exec build:sit script
13 verbose stack Error: vue-element-admin@3.10.0 build:sit: `cross-env NODE_ENV=production env_config=sit node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/server/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/server/node/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid vue-element-admin@3.10.0
15 verbose cwd /www/sun/app/public/admin
16 verbose Linux 3.10.0-693.el7.x86_64
17 verbose argv "/server/node/bin/node" "/server/node/bin/npm" "run" "build:sit"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-element-admin@3.10.0 build:sit: `cross-env NODE_ENV=production env_config=sit node build/build.js`
22 error Exit status 1
23 error Failed at the vue-element-admin@3.10.0 build:sit script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

#### Other relevant information（格外信息）
- Your OS: mac
- Node.js version:10.16.0
- vue-element-admin version: 3.10.0

**Comment by joelderrickclad** [comment]
I added **"C:\Windows\System32"** path to environment variable list and restarted the machine. It worked for me.

Please refer this [link ](https://stackoverflow.com/a/57511535/5352831)
