### ISSUE TITLE
npm run dev失败

### ISSUE THREAD

**Issue by icecooly** [PanJiaChen/vue-element-admin#236]
npm install
> fsevents@1.1.2 install /Users/skydu/Documents/vue/vue-element-admin-master/node_modules/fsevents
> node install

[fsevents] Success: "/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.5.3 install /Users/skydu/Documents/vue/vue-element-admin-master/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/skydu/.npm/node-sass/4.5.3/darwin-x64-57_binding.node

> node-sass@4.5.3 postinstall /Users/skydu/Documents/vue/vue-element-admin-master/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/skydu/Documents/vue/vue-element-admin-master/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
added 1228 packages in 104.07s
skydu@skydudeMacBook-Pro ~/D/v/vue-element-admin-master> npm run dev

> Starting dev server...
{ BrowserslistError: `browserlist` key instead of `browserslist` in /Users/skydu/Documents/vue/vue-element-admin-master/package.json
    at parsePackage (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/browserslist/index.js:109:11)
    at /Users/skydu/Documents/vue/vue-element-admin-master/node_modules/browserslist/index.js:401:27
    at eachParent (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/browserslist/index.js:85:18)
    at Function.browserslist.findConfig (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/browserslist/index.js:393:18)
    at browserslist (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/browserslist/index.js:235:38)
    at Browsers.parse (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/autoprefixer/lib/autoprefixer.js:67:24)
    at plugin (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/autoprefixer/lib/autoprefixer.js:78:24)
    at LazyResult.run (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/postcss/lib/lazy-result.js:270:20)
    at LazyResult.asyncTick (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/postcss/lib/lazy-result.js:185:32)
    at LazyResult.asyncTick (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/postcss/lib/lazy-result.js:197:22)
    at processing.Promise.then._this2.processed (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/postcss/lib/lazy-result.js:224:20)
    at Promise (<anonymous>)
    at LazyResult.async (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/postcss/lib/lazy-result.js:221:27)
    at LazyResult.then (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/postcss/lib/lazy-result.js:127:21)
    at loadPostcssConfig.then.config (/Users/skydu/Documents/vue/vue-element-admin-master/node_modules/vue-loader/lib/style-compiler/index.js:58:8)
    at <anonymous>

**Comment by icecooly** [comment]
之前是好的 奇怪

**Comment by PanJiaChen** [comment]
已修复 `browserlist key instead of browserslis` 问题

**Comment by icecooly** [comment]
试了 可以运行  但首页空白 一直在转圈

Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at permission.js:46
    at new Promise (<anonymous>)
    at new F (_export.js:35)
    at GenerateRoutes (permission.js:42)
    at Array.wrappedActionHandler (vuex.esm.js:598)
    at Store.dispatch (vuex.esm.js:341)
    at Store.boundDispatch [as dispatch] (vuex.esm.js:266)
    at permission.js:25
    at <anonymous>


貌似是role没读到是空的吧

**Comment by icecooly** [comment]
我还是下个release版本试试

**Comment by mysteryHJJ** [comment]
我也遇到了同样问题，之前还好好的

**Comment by PanJiaChen** [comment]
将 package.json 里面的 `browserlist`  改成  `browserslist`
