### ISSUE TITLE
启动项目报错了！求指导！

### ISSUE THREAD

**Issue by shuwangy** [PanJiaChen/vue-element-admin#2392]
vue-element-admin@4.2.1 dev E:\vue-element-admin
 vue-cli-service serve

:\vue-element-admin\node_modules\open\index.js:29
               ...options
               ^^^

yntaxError: Unexpected token ...
   at createScript (vm.js:74:10)
   at Object.runInThisContext (vm.js:116:10)
   at Module._compile (module.js:533:28)
   at Object.Module._extensions..js (module.js:580:10)
   at Module.load (module.js:503:32)
   at tryModuleLoad (module.js:466:12)
   at Function.Module._load (module.js:458:3)
   at Module.require (module.js:513:17)
   at require (internal/module.js:11:18)
   at Object.<anonymous> (E:\vue-element-admin\node_modules\@vue\cli-shared-uti
s\lib\openBrowser.js:9:14)
pm ERR! code ELIFECYCLE
pm ERR! errno 1
pm ERR! vue-element-admin@4.2.1 dev: `vue-cli-service serve`
pm ERR! Exit status 1
pm ERR!
pm ERR! Failed at the vue-element-admin@4.2.1 dev script.
pm ERR! This is probably not a problem with npm. There is likely additional log
ing output above.

pm ERR! A complete log of this run can be found in:
pm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-07-18T0
_01_32_310Z-debug.log
没想到还没开始就结束了..

**Comment by shuwangy** [comment]
已解决 是node版本太低了
