### ISSUE TITLE
启动报错 Error: EPERM: operation not permitted, open 'D:\JQ\vue\vue-element-admin-master\node_modules\.cache\@babel\register\.babel.7.0.0.development.json'

### ISSUE THREAD

**Issue by likejian01** [PanJiaChen/vue-element-admin#2448]
D:\JQ\vue\vue-element-admin-master>npm run dev

> vue-element-admin@4.2.1 dev D:\JQ\vue\vue-element-admin-master
> vue-cli-service serve

 INFO  Starting development server...
 10% building 2/2 modules 0 activefs.js:114
    throw err;
    ^

Error: EPERM: operation not permitted, open 'D:\JQ\vue\vue-element-admin-master\node_modules\.cache\@babel\register\.babel.7.0.0.development.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at save (D:\JQ\vue\vue-element-admin-master\node_modules\@babel\register\lib\cache.js:52:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@4.2.1 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@4.2.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\likejian\AppData\Roaming\npm-cache\_logs\2019-08-06T09_11_17_854Z-debug.log

纠结了一天了。有没有大神路过  EPERM: operation not permitted 网上各种方法都试了。都不好使。急

**Comment by miduoN** [comment]
解决了吗
