### ISSUE TITLE
npm run dev直接报错无法运行 SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by LeeHeiHei** [PanJiaChen/vue-element-admin#2580]
## Bug report（问题描述）
npm run dev 报错
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\LDProject\Demo\vue-element-admin\node_modules\@vue\cli-shared-utils\lib\openBrowser.js:9:14)
npm ERR! code ELIFECYCLE

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by hery008** [comment]
我也遇到了这个问题，同求教。。。

**Comment by hery008** [comment]
同样遇到这种问题，可能是node版本太低了，你可以看下你的 node -v 版本。
重装或者升级node.js,
最后cnpm/npm install 就可以运行了
