### ISSUE TITLE
关于npm install 报错问题，参考方法如下

### ISSUE THREAD

**Issue by tiezhusu** [PanJiaChen/vue-element-admin#2621]
如果你是npm install之后，大量报错的话，大概率是跟我一样的问题，我的解决方法可能适合你。

```
// 建议另建一个新的文件夹，在cmd中依次执行以下步骤

git clone https://github.com/PanJiaChen/vue-element-admin.git

cd vue-element-admin

npm install --registry=https://registry.npm.taobao.org
// npm install这一步是关键，需要使用taobao这个源。

          // 若无报错，则可启动项目
          npm run dev 

          //如果依然存在报错，那么执行下列步骤
          npm uninstall node-sass
          npm i node-sass --sass_binary_site=https://npm.taobao.org/mirrors/node-sass
         // 这时候基本就能成功了，应该是不同源及版本出入的问题。
```

**Comment by monkeycf** [comment]
npm install后出现报错，尝试 npm uninstall node-sass 也出现大量报错
根据cmd的提示，将npm uninstall node-sass命令修改为 npm uninstall taskfile，再重新安装node-sass成功。

**Comment by Thinking80s** [comment]
#npm install cnpm -g --registry=https://registry.npm.taobao.org

cnpm install yorkie --save-dev
cnpm install sass-loader --save-dev
cnpm install node-sass --save-dev
cnpm install 

# 打包正式环境
npm run build:prod

个人这样操作才正常打包执行

**Comment by Veitor** [comment]
`yorkie` 相关的错误有人遇到没？

**Comment by dw1414739804** [comment]
试过上面所有的方法，没生效，
终于参考上面方法，找到了一个有效方法，把node升到最新版本，然后npm install --registry=https://registry.npm.taobao.org，然后npm run dev就可以了

**Comment by MX-Steve** [comment]
> npm install --registry=https://registry.npm.taobao.org

你 node 是什么版本的，我目前是 node16.13.1的，安装还报错

**Comment by MX-Steve** [comment]
npm ERR! code 1
npm ERR! path /app/cmdb_frontend/node_modules/deasync
npm ERR! command failed
npm ERR! command sh -c node ./build.js
npm ERR! `linux-x64-node-16` exists; testing
npm ERR! Problem with the binary; manual build incoming
npm ERR! stdout=
npm ERR! err=Error: Command failed: /app/node-v16.13.1-linux-x64/bin/node quick-test.js
npm ERR! /app/cmdb_frontend/node_modules/bindings/bindings.js:135
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Could not locate the bindings file. Tried:
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/build/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/build/Debug/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/build/Release/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/out/Debug/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/Debug/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/out/Release/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/Release/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/build/default/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/compiled/16.13.1/linux/x64/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/addon-build/release/install-root/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/addon-build/debug/install-root/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/addon-build/default/install-root/deasync.node
npm ERR!  → /app/cmdb_frontend/node_modules/deasync/lib/binding/node-v93-linux-x64/deasync.node
npm ERR!     at bindings (/app/cmdb_frontend/node_modules/bindings/bindings.js:126:9)
npm ERR!     at Object.<anonymous> (/app/cmdb_frontend/node_modules/deasync/index.js:30:31)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (/app/cmdb_frontend/node_modules/deasync/quick-test.js:3:13)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14) {
npm ERR!   tries: [
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/build/deasync.node',
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/build/Debug/deasync.node',
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/build/Release/deasync.node',
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/out/Debug/deasync.node',
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/Debug/deasync.node',
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/out/Release/deasync.node',
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/Release/deasync.node',
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/build/default/deasync.node',
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/compiled/16.13.1/linux/x64/deasync.node',
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/addon-build/release/install-root/deasync.node',     
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/addon-build/debug/install-root/deasync.node',       
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/addon-build/default/install-root/deasync.node',     
npm ERR!     '/app/cmdb_frontend/node_modules/deasync/lib/binding/node-v93-linux-x64/deasync.node'        
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! make: Entering directory `/app/cmdb_frontend/node_modules/deasync/build'
npm ERR!   CXX(target) Release/obj.target/deasync/src/deasync.o
npm ERR! make: Leaving directory `/app/cmdb_frontend/node_modules/deasync/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.0 found at "/usr/local/bin/python3"
npm ERR! gyp info spawn /usr/local/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/app/node-v16.13.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/app/cmdb_frontend/node_modules/deasync/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/app/node-v16.13.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.13.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/app/node-v16.13.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.13.1/<(target_arch)/node.lib',   
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/app/cmdb_frontend/node_modules/deasync',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error: unrecognized command line option '-std=gnu++14'
npm ERR! make: *** [Release/obj.target/deasync/src/deasync.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/app/node-v16.13.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)   
npm ERR! gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
npm ERR! gyp ERR! command "/app/node-v16.13.1-linux-x64/bin/node" "/app/node-v16.13.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /app/cmdb_frontend/node_modules/deasync
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed
