### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by yangyiyuan** [PanJiaChen/vue-element-admin#2790]
~~~
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.10.2
3 info using node@v12.7.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-element-admin@4.2.1~predev: vue-element-admin@4.2.1
6 info lifecycle vue-element-admin@4.2.1~dev: vue-element-admin@4.2.1
7 verbose lifecycle vue-element-admin@4.2.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-element-admin@4.2.1~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vagrant/code/SmartCityFrontEnd/node_modules/.bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle vue-element-admin@4.2.1~dev: CWD: /home/vagrant/code/SmartCityFrontEnd
10 silly lifecycle vue-element-admin@4.2.1~dev: Args: [ '-c', 'vue-cli-service serve' ]
11 info lifecycle vue-element-admin@4.2.1~dev: Failed to exec dev script
12 verbose stack Error: vue-element-admin@4.2.1 dev: `vue-cli-service serve`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:203:13)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid vue-element-admin@4.2.1
14 verbose cwd /home/vagrant/code/SmartCityFrontEnd
15 verbose Linux 4.15.0-55-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
17 verbose node v12.7.0
18 verbose npm  v6.10.2
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error vue-element-admin@4.2.1 dev: `vue-cli-service serve`
23 error spawn ENOENT
24 error Failed at the vue-element-admin@4.2.1 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
vagrant@homestead:~/code/SmartCityFrontEnd$ node -v
v12.7.0
vagrant@homestead:~/code/SmartCityFrontEnd$ npm -v
6.10.2
~~~
搞了半天，前边安装总算过去了，但是运行的时候一直报错，实在是没搜到相关的信息。
大神帮忙看下。

**Comment by sunpu007** [comment]
初步判断是你的依赖安装错误问题
`
rm -rf node_modules
rm package-lock.json
npm cache clear --force
npm install
`

**Comment by CharlesZHENG** [comment]
> ```
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
> 2 info using npm@6.10.2
> 3 info using node@v12.7.0
> 4 verbose run-script [ 'predev', 'dev', 'postdev' ]
> 5 info lifecycle vue-element-admin@4.2.1~predev: vue-element-admin@4.2.1
> 6 info lifecycle vue-element-admin@4.2.1~dev: vue-element-admin@4.2.1
> 7 verbose lifecycle vue-element-admin@4.2.1~dev: unsafe-perm in lifecycle true
> 8 verbose lifecycle vue-element-admin@4.2.1~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vagrant/code/SmartCityFrontEnd/node_modules/.bin:/usr/games:/usr/local/games:/snap/bin
> 9 verbose lifecycle vue-element-admin@4.2.1~dev: CWD: /home/vagrant/code/SmartCityFrontEnd
> 10 silly lifecycle vue-element-admin@4.2.1~dev: Args: [ '-c', 'vue-cli-service serve' ]
> 11 info lifecycle vue-element-admin@4.2.1~dev: Failed to exec dev script
> 12 verbose stack Error: vue-element-admin@4.2.1 dev: `vue-cli-service serve`
> 12 verbose stack spawn ENOENT
> 12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
> 12 verbose stack     at ChildProcess.emit (events.js:203:13)
> 12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
> 13 verbose pkgid vue-element-admin@4.2.1
> 14 verbose cwd /home/vagrant/code/SmartCityFrontEnd
> 15 verbose Linux 4.15.0-55-generic
> 16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
> 17 verbose node v12.7.0
> 18 verbose npm  v6.10.2
> 19 error file sh
> 20 error code ELIFECYCLE
> 21 error errno ENOENT
> 22 error syscall spawn
> 23 error vue-element-admin@4.2.1 dev: `vue-cli-service serve`
> 23 error spawn ENOENT
> 24 error Failed at the vue-element-admin@4.2.1 dev script.
> 24 error This is probably not a problem with npm. There is likely additional logging output above.
> 25 verbose exit [ 1, true ]
> vagrant@homestead:~/code/SmartCityFrontEnd$ node -v
> v12.7.0
> vagrant@homestead:~/code/SmartCityFrontEnd$ npm -v
> 6.10.2
> ```
> 
> 搞了半天，前边安装总算过去了，但是运行的时候一直报错，实在是没搜到相关的信息。
> 大神帮忙看下。
问题解决了吗，怎么解决的，我也遇到了。
