### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by briefness** [PanJiaChen/vue-element-admin#281]
我已经翻墙了
直接npm install 报错，然后npm run dev 失败

**Comment by PanJiaChen** [comment]
请提供详细信息

**Comment by YangPengFe1** [comment]
```
F:\VUE\end-demo\vue-element-admin>npm i

> node-sass@4.6.1 install F:\VUE\end-demo\vue-element-admin\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.6.1/win32-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.6.1/win32-x64-48_binding.node":

connect ETIMEDOUT 52.216.18.16:443

Timed out whilst downloading the prebuilt binary

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.6.1 postinstall F:\VUE\end-demo\vue-element-admin\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe F:\VUE\end-demo\vue-element-admin\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsa
ss_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@6.11.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\wh
ich\\which.js:13:12)\n    at F (F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\which\\which.js:68:19)\n    at E (F:\\VUE\\end-demo\\vue
-element-admin\\node_modules\\which\\which.js:80:29)\n    at F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\which\\which.js:89:16\n
at F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\isexe\\index.js:42:5\n    at F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\isex
e\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files\Python36\python.EXE
gyp verb check python version `C:\Program Files\Python36\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.
1\r\n"
gyp verb could not find "C:\Program Files\Python36\python.EXE". checking python launcher
gyp verb could not find "C:\Program Files\Python36\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Program Files\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (F:\VUE\end-demo\vue-element-admin\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (F:\VUE\end-demo\vue-element-admin\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at F:\VUE\end-demo\vue-element-admin\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd F:\VUE\end-demo\vue-element-admin\node_modules\node-sass
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN Error: EPERM: operation not permitted, scandir 'F:\VUE\end-demo\vue-element-admin\node_modules\wide-align\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, scandir 'F:\VUE\end-demo\vue-element-admin\node_modules\wide-align\node_modules'
npm WARN     at Error (native)
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\wide-align\\node_mod
ules\'\n    at Error (native)',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\wide-align\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.6.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.6.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-11-14T13_35_51_622Z-debug.log
```
> 执行npm i 之后报错  但是我确保 我vue-cli没有问题。有没有同样的问题的人。

**Comment by YangPengFe1** [comment]
```
F:\VUE\end-demo\vue-element-admin>npm i

> node-sass@4.6.1 install F:\VUE\end-demo\vue-element-admin\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.6.1/win32-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.6.1/win32-x64-48_binding.node":

connect ETIMEDOUT 52.216.18.16:443

Timed out whilst downloading the prebuilt binary

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.6.1 postinstall F:\VUE\end-demo\vue-element-admin\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe F:\VUE\end-demo\vue-element-admin\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsa
ss_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@6.11.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\VUE\end-demo\vue-element-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\wh
ich\\which.js:13:12)\n    at F (F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\which\\which.js:68:19)\n    at E (F:\\VUE\\end-demo\\vue
-element-admin\\node_modules\\which\\which.js:80:29)\n    at F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\which\\which.js:89:16\n
at F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\isexe\\index.js:42:5\n    at F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\isex
e\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files\Python36\python.EXE
gyp verb check python version `C:\Program Files\Python36\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.
1\r\n"
gyp verb could not find "C:\Program Files\Python36\python.EXE". checking python launcher
gyp verb could not find "C:\Program Files\Python36\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Program Files\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (F:\VUE\end-demo\vue-element-admin\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (F:\VUE\end-demo\vue-element-admin\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at F:\VUE\end-demo\vue-element-admin\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd F:\VUE\end-demo\vue-element-admin\node_modules\node-sass
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN Error: EPERM: operation not permitted, scandir 'F:\VUE\end-demo\vue-element-admin\node_modules\wide-align\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, scandir 'F:\VUE\end-demo\vue-element-admin\node_modules\wide-align\node_modules'
npm WARN     at Error (native)
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\wide-align\\node_mod
ules\'\n    at Error (native)',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'F:\\VUE\\end-demo\\vue-element-admin\\node_modules\\wide-align\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.6.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.6.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-11-14T13_35_51_622Z-debug.log
```
> 执行npm i 之后报错  但是我确保 我vue-cli没有问题。有没有同样的问题的人。

**Comment by YangPengFe1** [comment]
采用cnpm安装 没有错误。

**Comment by PanJiaChen** [comment]
Closing for inactivity.
node-sass 的安装错误请自行搜索解决方案。

**Comment by FroilanYue** [comment]
This works for me:
`npm install --unsafe-perm=true --allow-root`
see: [stackoverflow!52715548](https://stackoverflow.com/a/52715548/6116330)
