### ISSUE TITLE
在阿里云上执行报错，是因为node版本太低吗？

### ISSUE THREAD

**Issue by wangzboo** [PanJiaChen/vue-element-admin#2815]
## Question（提问）
按步骤在阿里云执行后，一直报错，看了很多的解决方法，都没有用。是因为node版本太低了吗。

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/39321118/70231447-4c8b8780-1795-11ea-814f-262f3405a32b.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by wangzboo** [comment]
图片看不到，这是报错信息。
[root@izuf6fj6g4fqhy6ag7xggpz vue-admin-template]#  npm run dev

> vue-admin-template@4.2.1 dev /root/vue-admin-template
> vue-cli-service serve

/root/vue-admin-template/node_modules/@vue/cli-service/bin/vue-cli-service.js:4
const { error } = require('@vue/cli-shared-utils')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/local/node/node-v4.4.7-linux-x64/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.4.7
npm ERR! npm  v3.3.1
npm ERR! code ELIFECYCLE
npm ERR! vue-admin-template@4.2.1 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-admin-template@4.2.1 dev script 'vue-cli-service serve'.
npm ERR! This is most likely a problem with the vue-admin-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls vue-admin-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/vue-admin-template/npm-debug.log

**Comment by wangzboo** [comment]
cd /usr/local/node/

wget https://cdn.npm.taobao.org/dist/node/latest/node-v9.9.0-linux-x64.tar.gz

ln -s /usr/local/node/node-v9.9.0-linux-x64/bin/npm /usr/local/bin/npm
ln -s /usr/local/node/node-v9.9.0-linux-x64/bin/node /usr/local/bin/node

npm install --registry=https://registry.npm.taobao.org --unsafe-perm

升级了可以用了。然后把目录都改成777，再用最后这个命令执行成功了。
