### ISSUE TITLE
linux系统下，访问页面的时候报错

### ISSUE THREAD

**Issue by xiaohuihuiye** [PanJiaChen/vue-element-admin#2924]
## Bug report（问题描述）
系统版本：
Linux yehh-PC 4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018 x86_64 GNU/Linux

#### Steps to reproduce（问题复现步骤）
1. 
安装依赖，当运行npm install没有提示错误，只有一些警告

####
当前端访问　http://localhost:9528/　时候报错如下：

Failed to compile.

./src/layout/index.vue?vue&type=style&index=0&id=13877386&lang=scss&scoped=true& (./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layout/index.vue?vue&type=style&index=0&id=13877386&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding /app/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/app/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at getDefaultSassImpl (/app/node_modules/sass-loader/dist/index.js:198:10)
    at Object.loader (/app/node_modules/sass-loader/dist/index.js:80:29)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:　v8.11.2
- vue-element-admin version　:2.9.6

**Comment by PanJiaChen** [comment]
报错提示很明确了。
