### ISSUE TITLE
在cli@4.x下面报错，现在不支持cli@4.x？

### ISSUE THREAD

**Issue by tomsure** [PanJiaChen/vue-element-admin#3166]
在cli@4.x下面报错，现在不支持cli@4.x吗？

#### Steps to reproduce（问题复现步骤）

1. 克隆代码
2. 安装依赖
3. 启动

```javascript

E:\vue-element-admin>"node"  "E:\vue-element-admin\node_modules\.bin\\..\_@vue_cli-service@3.6.0@@vue\cli-service\bin\vue-cli-service.js" serve --open
 ERROR  Error loading vue.config.js:
 ERROR  Error: Cannot find module 'body-parser'
 Require stack:
- E:\vue-element-admin\mock\mock-server.js
- E:\vue-element-admin\vue.config.js
- E:\vue-element-admin\node_modules\_@vue_cli-service@3.6.0@@vue\cli-service\lib\Service.js
- E:\vue-element-admin\node_modules\_@vue_cli-service@3.6.0@@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module 'body-parser'
Require stack:
- E:\vue-element-admin\mock\mock-server.js
- E:\vue-element-admin\vue.config.js
- E:\vue-element-admin\node_modules\_@vue_cli-service@3.6.0@@vue\cli-service\lib\Service.js
- E:\vue-element-admin\node_modules\_@vue_cli-service@3.6.0@@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\vue-element-admin\mock\mock-server.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)

tomsure@tangxu MINGW64 /e/vue-element-admin (master)
$ vue --version
@vue/cli 4.2.3
```
#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/15616904/81424300-49ebee80-9188-11ea-812f-095b22c7090d.png)

**Comment by PanJiaChen** [comment]
你是少装了依赖吧，npm install 一下

**Comment by tomsure** [comment]
删除后重新拉了代码，重新npm install 发现依赖始终装不完整就中断了 
![image](https://user-images.githubusercontent.com/15616904/81462849-f610f200-91e7-11ea-863c-5ed336fcfe28.png)
![image](https://user-images.githubusercontent.com/15616904/81462856-fad5a600-91e7-11ea-81b2-c2055a3622aa.png)

**Comment by tomsure** [comment]
很多遍都这样

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/24

**Comment by tomsure** [comment]
可以了，谢谢
