### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by KenNaNa** [PanJiaChen/vue-element-admin#3488]
$ yarn install
yarn install v1.22.10
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning element-ui > async-validator > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning jsonlint > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
error An unexpected error occurred: "https://github.com/sohee-lee7/Squire: read ECONNRESET".
info If you think this is a bug, please open a bug report with the information provided in "F:\\鑷繁鐨勫伐浣淺\work\\vue-element-admin\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Command failed.
Exit code: 1
Command: git
Arguments: pull
Directory: C:\Users\Administrator\AppData\Local\Yarn\Cache\v6\.tmp\60cb5dac1cfafc1829af48c5dc5fdf3f
Output:
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
    at ProcessTermError.ExtendableBuiltin (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:721:66)
    at ProcessTermError.MessageError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:750:123)
    at new ProcessTermError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:790:113)
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:25884:17)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by 775728212** [comment]
同问

**Comment by iefhong** [comment]
试试更改package.json
```json
 "tui-editor": "1.4.10",
```
添加yarn代理

我的 node 版本为 12.22.7
