### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by junyussh** [PanJiaChen/vue-element-admin#3543]
## Bug report（问题描述）

npm install got errors

#### Steps to reproduce（问题复现步骤）

I ran `npm install` first, then it throw some errors below.

![image](https://user-images.githubusercontent.com/11587044/101634348-84da3b80-3a63-11eb-9ada-dce30026e16b.png)

Then, I ran ` npm install --legacy-peer-deps` and got these errors.

```
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/nhn/raphael.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

#### Other relevant information（格外信息）
- Your OS: Windows 10
- Node.js version: v14.15.1
- vue-element-admin version:

**Comment by junyussh** [comment]
Using yarn can solve the problem. Just type `yarn` to install requirements.

**Comment by jizhujian** [comment]
npm install -g yarn

**Comment by zhangopeng** [comment]
node version：14.16.1 ;   you can try it

**Comment by LayneChai** [comment]
I also get the error message， then  type yarn install  to install requirements，but i get some error messages

`Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/nhn/raphael.git
Directory: C:\Users\93676\Desktop\SpringCloud-Admin-master
Output:
fatal: unable to access 'https://github.com/nhn/raphael.git/': OpenSSL SSL_read: Connection was reset, errno 10054
    at ProcessTermError.ExtendableBuiltin (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:721:66)
    at ProcessTermError.MessageError (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:750:123)
    at new ProcessTermError (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:790:113)
    at ChildProcess.<anonymous> (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:25888:17)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)`

**Comment by LayneChai** [comment]
I also get the error message， then  type yarn install  to install requirements，but i get some error messages

`Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/nhn/raphael.git
Directory: C:\Users\93676\Desktop\SpringCloud-Admin-master
Output:
fatal: unable to access 'https://github.com/nhn/raphael.git/': OpenSSL SSL_read: Connection was reset, errno 10054
    at ProcessTermError.ExtendableBuiltin (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:721:66)
    at ProcessTermError.MessageError (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:750:123)
    at new ProcessTermError (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:790:113)
    at ChildProcess.<anonymous> (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:25888:17)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)`

**Comment by LayneChai** [comment]
I also get the error message， then  type yarn install  to install requirements，but i get some error messages

`
Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/nhn/raphael.git
Directory: C:\Users\93676\Desktop\SpringCloud-Admin-master
Output:
fatal: unable to access 'https://github.com/nhn/raphael.git/': OpenSSL SSL_read: Connection was reset, errno 10054
    at ProcessTermError.ExtendableBuiltin (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:721:66)
    at ProcessTermError.MessageError (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:750:123)
    at new ProcessTermError (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:790:113)
    at ChildProcess.<anonymous> (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:25888:17)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
`

**Comment by LayneChai** [comment]
I also get the error message， then  type yarn install  to install requirements，but i get some error messages

`Error: Command failed. \n
Exit code: 128 \n
Command: git
Arguments: ls-remote --tags --heads https://github.com/nhn/raphael.git
Directory: C:\Users\93676\Desktop\SpringCloud-Admin-master
Output:
fatal: unable to access 'https://github.com/nhn/raphael.git/': OpenSSL SSL_read: Connection was reset, errno 10054
    at ProcessTermError.ExtendableBuiltin (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:721:66)
    at ProcessTermError.MessageError (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:750:123)
    at new ProcessTermError (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:790:113)
    at ChildProcess.<anonymous> (E:\npmRepository\npm-global\node_modules\yarn\lib\cli.js:25888:17)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)`

**Comment by SunLemuria** [comment]
this works for me: generate ssh key and add public key to GitHub
