### ISSUE TITLE
npm install error 安装依赖失败

### ISSUE THREAD

**Issue by Benution** [PanJiaChen/vue-element-admin#3624]
#### Steps to reproduce（问题复现步骤）
9594 error gyp ERR! configure error
9594 error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
9594 error gyp ERR! stack     at PythonFinder.failNoPython (D:\王天矢\test\vue-element-admin\node_modules\node-gyp\lib\configure.js:484:19)
9594 error gyp ERR! stack     at PythonFinder.<anonymous> (D:\王天矢\test\vue-element-admin\node_modules\node-gyp\lib\configure.js:509:16)
9594 error gyp ERR! stack     at callback (D:\王天矢\test\vue-element-admin\node_modules\graceful-fs\polyfills.js:299:20)
9594 error gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
9594 error gyp ERR! System Windows_NT 6.1.7601
9594 error gyp ERR! command "D:\\Node.js\\node.exe" "D:\\王天矢\\test\\vue-element-admin\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
9594 error gyp ERR! cwd D:\王天矢\test\vue-element-admin\node_modules\canvas
9594 error gyp ERR! node -v v12.16.2
9594 error gyp ERR! node-gyp -v v3.8.0
9594 error gyp ERR! not ok
9595 verbose exit 1

#### Screenshot or Gif（截图或动态图）
![QQ截图20210303163218](https://user-images.githubusercontent.com/50387965/109777313-8cfadf00-7c3e-11eb-91a1-6285fbdcc39a.png)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:

**Comment by Benution** [comment]
> ## Question（提问）
> #### Steps to reproduce（问题复现步骤）
> 9594 error gyp ERR! configure error
> 9594 error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> 9594 error gyp ERR! stack at PythonFinder.failNoPython (D:\王天矢\test\vue-element-admin\node_modules\node-gyp\lib\configure.js:484:19)
> 9594 error gyp ERR! stack at PythonFinder. (D:\王天矢\test\vue-element-admin\node_modules\node-gyp\lib\configure.js:509:16)
> 9594 error gyp ERR! stack at callback (D:\王天矢\test\vue-element-admin\node_modules\graceful-fs\polyfills.js:299:20)
> 9594 error gyp ERR! stack at FSReqCallback.oncomplete (fs.js:167:21)
> 9594 error gyp ERR! System Windows_NT 6.1.7601
> 9594 error gyp ERR! command "D:\Node.js\node.exe" "D:\王天矢\test\vue-element-admin\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> 9594 error gyp ERR! cwd D:\王天矢\test\vue-element-admin\node_modules\canvas
> 9594 error gyp ERR! node -v v12.16.2
> 9594 error gyp ERR! node-gyp -v v3.8.0
> 9594 error gyp ERR! not ok
> 9595 verbose exit 1
> 
> #### Screenshot or Gif（截图或动态图）
>
> 
> #### Other relevant information（格外信息）
> * Your OS:
> * Node.js version:
> * vue-element-admin version:

**Comment by Benution** [comment]
是win7系统

**Comment by apocalypseChenyq** [comment]
没有Python环境， 下载Python2.X版本

**Comment by ryuukinken** [comment]
请问解决了吗 我现在也是这个问题

**Comment by Benution** [comment]
> 请问解决了吗 我现在也是这个问题

安装一下python环境。 2或者3都可以
