### ISSUE TITLE
这是怎么回事啊，安装了phthon2.7，配置了环境，也按照了node-sass 和sass-loader

### ISSUE THREAD

**Issue by 3022317607** [PanJiaChen/vue-element-admin#3642]
npm ERR! code 7
npm ERR! path C:\Users\jk\Desktop\Vue\front\vue-admin-template-master\vue-admin-template\node_modules\fibers
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@14.16.0 | win32 | x64
npm ERR! gyp info spawn C:\appList\Python\python.EXE
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\jk\\Desktop\\Vue\\front\\vue-admin-template-master\\vue-admin-template\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2015',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\jk\\Desktop\\Vue\\front\\vue-admin-template-master\\vue-admin-template\\node_modules\\fibers\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\jk\\Desktop\\Vue\\front\\vue-admin-template-master\\vue-admin-template\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\jk\\.node-gyp\\14.16.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jk\\.node-gyp\\14.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jk\\Desktop\\Vue\\front\\vue-admin-template-master\\vue-admin-template\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\jk\\.node-gyp\\14.16.0\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\jk\\Desktop\\Vue\\front\\vue-admin-template-master\\vue-admin-template\\node_modules\\fibers',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\jk\\Desktop\\Vue\\front\\vue-admin-template-master\\vue-admin-template\\node_modules\\fibers\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
npm ERR! gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\appList\\node.js\\node.exe" "C:\\Users\\jk\\Desktop\\Vue\\front\\vue-admin-template-master\\vue-admin-template\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\jk\Desktop\Vue\front\vue-admin-template-master\vue-admin-template\node_modules\fibers
npm ERR! gyp ERR! node -v v14.16.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

**Comment by apocalypseChenyq** [comment]
安装gyp
npm install -g node-gyp

**Comment by buladmin** [comment]
建议在文档中追加这项安装步骤

**Comment by 3022317607** [comment]
我把关于node.js的一系列文件删除了，卸载了node.js，然后重新安装node.js发现就有用了

**Comment by azhen98** [comment]
### 去看下 sass的版本你就知道为什么会报错了
