### ISSUE TITLE
Centos 7.7 上安装报错

### ISSUE THREAD

**Issue by yanxiaowuchris** [PanJiaChen/vue-element-admin#3782]
7147 timing idealTree:buildDeps Completed in 349845ms
7148 timing idealTree:fixDepFlags Completed in 62ms
7149 timing idealTree Completed in 349931ms
7150 timing command:install Completed in 349962ms
7151 verbose stack Error: An unknown git error occurred
7151 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
7151 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:36:26
7151 verbose stack     at runMicrotasks (<anonymous>)
7151 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
7152 verbose cwd /vueCode/vue-element-admin-master
7153 verbose Linux 3.10.0-1062.el7.x86_64
7154 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
7155 verbose node v16.6.1
7156 verbose npm  v7.20.3
7157 error code 128
7158 error An unknown git error occurred
7159 error command git --no-replace-objects ls-remote ssh://git@github.com/nhn/raphael.git
7160 **error Warning: Permanently added 'github.com,20.205.243.166' (RSA) to the list of known hosts.**
7160 error Permission denied (publickey).
7160 error fatal: Could not read from remote repository.
7160 error
7160 error Please make sure you have the correct access rights
7160 error and the repository exists.
7161 verbose exit 128

**Comment by yanxiaowuchris** [comment]
自己查到啦，  这个问题说 被github。com 拒绝了，我试验了一下www.github.com能访问，网上搜索后发现可能是 证书过期导致的，重新生成证书，并且需要使用帐号登陆 www.github.com ，在 个人配置中 settings 里面 有个ssh key的菜单中 添加key，将本地生成的证书公匙拷贝到网页中，保存即可。
就是说，每一个访问www.githum.com的客户端 的公匙，www.github.com 需要提前登记，你说坑不坑
