### ISSUE TITLE
npm run dev 运行项目失败

### ISSUE THREAD

**Issue by oneplus8t-at** [PanJiaChen/vue-element-admin#3857]
- E:\es\vue-element-admin-master\node_modules\@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module 'body-parser'
Require stack:
- E:\es\vue-element-admin-master\mock\mock-server.js
- E:\es\vue-element-admin-master\vue.config.js
- E:\es\vue-element-admin-master\node_modules\@vue\cli-service\node_modules\@vue\cli-shared-utils\lib\module.js
- E:\es\vue-element-admin-master\node_modules\@vue\cli-service\node_modules\@vue\cli-shared-utils\index.js
- E:\es\vue-element-admin-master\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\es\vue-element-admin-master\mock\mock-server.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@4.4.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@4.4.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2021-10-27T06_59_17_393Z-debug.log

**Comment by chuichui9527** [comment]
重新npm  install 一下

**Comment by GAtomis** [comment]
lock也删除在重新安装下

**Comment by Gema-uestc** [comment]
I found the solution [Here](https://github.com/uuidjs/uuid/issues/488#issuecomment-699484348)
Upgrade to node 14 and it worked.

**Comment by Tiper-In-Github** [comment]
国际的包坏掉了，换淘宝源就可以解决了。亲测可用

**Comment by Tiper-In-Github** [comment]
项目依赖太老了，国际的包坏掉了，换淘宝源就可以解决了。亲测可用：参考https://blog.csdn.net/weixin_43843901/article/details/117531670
