### ISSUE TITLE
npm run dev时出错

### ISSUE THREAD

**Issue by lelozlc** [PanJiaChen/vue-element-admin#3882]
Node.js版本: v14.17.1
下面报错这个uuid 的版本是8.3.2,我在网上看是版本不匹配,请问大家用的什么版本,有出现这个问题吗 ?

vue-element-admin@4.4.0 dev D:\CodeSapce\vueCodeSpace\study-project\vue-element-admin
> vue-cli-service serve
INFO  Starting development server...
ERROR  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in D:\CodeSapce\vueCodeSpace\study-project\vue-element-admin\node_modules\sockjs\node_modules\uuid\package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in D:\CodeSapce\vueCodeSpace\study-project\vue-element-admin\node_modules\sockjs\node_modules\uuid\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\CodeSapce\vueCodeSpace\study-project\vue-element-admin\node_modules\sockjs\lib\transport.js:9:12)
    at Object.<anonymous> (D:\CodeSapce\vueCodeSpace\study-project\vue-element-admin\node_modules\sockjs\lib\transport.js:438:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@4.4.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@4.4.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Tools\NodeJs\node_cache\_logs\2021-12-03T01_48_58_878Z-debug.log

**Comment by Gema-uestc** [comment]
Node 版本用14
