### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Codelifeguardian** [PanJiaChen/vue-element-admin#3974]
## Question（提问）

最开始提示 python 环境缺失，配置后(python3.9)重新 npm install；
接着提示 node-v16.14.2-headers.tar.gz 下载失败，解决后重新 npm install；
接着提示 Could not find any Visual Studio installation to use，解决后重新 npm install;
接着 FetchError: request to https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt failed
然后，请帮帮我，我绷不住了 ...

### 错误信息

npm ERR! code 1
npm ERR! path D:\Web_PRO\vue-element-admin\node_modules\deasync
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.7 found at "D:\A-SOFTWARE\Anaconda3\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/win-arm64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.2/win-x86/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.2/win-x64/node.lib
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt failed, reason: read ECONNRESET
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (D:\A-SOFTWARE\node\node-v16.14.2-win-x64\node_modules\npm\node_modules\minipass-fetch\lib\index.js:110:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:442:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:538:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "D:\\A-SOFTWARE\\node\\node-v16.14.2-win-x64\\node.exe" "D:\\A-SOFTWARE\\node\\node-v16.14.2-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\Web_PRO\vue-element-admin\node_modules\deasync
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

### Other relevant information（格外信息）
- OS: win10
- Node.js version: v16.14.2
- vue-element-admin version:

**Comment by ChenMeng-1919** [comment]
切换回官方镜像重新安装，虽然还是报错但是能跑了
npm config set registry https://registry.npmjs.org/

**Comment by Codelifeguardian** [comment]
> 切换回官方镜像重新安装，虽然还是报错但是能跑了 npm config set registry https://registry.npmjs.org/

试过了，不行。npm install 失败直接回滚了就。

**Comment by Codelifeguardian** [comment]
我现在就希望知道一套能跑起来的环境版本...

**Comment by jzfai** [comment]
vue-element-admin vue2版 存在很多问题 直接用 vue3版本不香吗

**Comment by jzfai** [comment]
vue-element-admin vue2版 存在很多问题 直接用 vue3版本不香吗 https://github.com/jzfai/vue3-admin-plus

**Comment by chenboxiaoxiao** [comment]
和这些都没有关系，用nvm把node的版本调整为12.13.1，然后重新npm i，绝对能跑起来，你node版本太高了

**Comment by SeanLuis** [comment]
> ## Question（提问）
> 最开始提示 python 环境缺失，配置后(python3.9)重新 npm install； 接着提示 node-v16.14.2-headers.tar.gz 下载失败，解决后重新 npm install； 接着提示 Could not find any Visual Studio installation to use，解决后重新 npm install; 接着 FetchError: request to https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt failed 然后，请帮帮我，我绷不住了 ...
> 
> ### 错误信息
> npm ERR! code 1 npm ERR! path D:\Web_PRO\vue-element-admin\node_modules\deasync npm ERR! command failed npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild npm ERR! gyp info it worked if it ends with ok npm ERR! gyp info using node-gyp@8.4.1 npm ERR! gyp info using node@16.14.2 | win32 | x64 npm ERR! gyp info find Python using Python version 3.9.7 found at "D:\A-SOFTWARE\Anaconda3\python.exe" npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/win-x86/node.lib npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/win-arm64/node.lib npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/win-x64/node.lib npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.2/win-x86/node.lib npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.2/win-x64/node.lib npm ERR! gyp WARN install got an error, rolling back install npm ERR! gyp ERR! configure error npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt failed, reason: read ECONNRESET npm ERR! gyp ERR! stack at ClientRequest. (D:\A-SOFTWARE\node\node-v16.14.2-win-x64\node_modules\npm\node_modules\minipass-fetch\lib\index.js:110:14) npm ERR! gyp ERR! stack at ClientRequest.emit (node:events:526:28) npm ERR! gyp ERR! stack at TLSSocket.socketErrorListener (node:_http_client:442:9) npm ERR! gyp ERR! stack at TLSSocket.emit (node:events:538:35) npm ERR! gyp ERR! stack at emitErrorNT (node:internal/streams/destroy:157:8) npm ERR! gyp ERR! stack at emitErrorCloseNT (node:internal/streams/destroy:122:3) npm ERR! gyp ERR! stack at processTicksAndRejections (node:internal/process/task_queues:83:21) npm ERR! gyp ERR! System Windows_NT 10.0.19044 npm ERR! gyp ERR! command "D:\A-SOFTWARE\node\node-v16.14.2-win-x64\node.exe" "D:\A-SOFTWARE\node\node-v16.14.2-win-x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" npm ERR! gyp ERR! cwd D:\Web_PRO\vue-element-admin\node_modules\deasync npm ERR! gyp ERR! node -v v16.14.2 npm ERR! gyp ERR! node-gyp -v v8.4.1 npm ERR! gyp ERR! not ok
> 
> ### Other relevant information（格外信息）
> * OS: win10
> * Node.js version: v16.14.2
> * vue-element-admin version:

Si estas usando windows te reomiendo que instales las herrmaientas de desarrollo para escritorio de Visual Studio (La version que concuerde con Python 3.9.7). Te instalara lo necesario para que puedas correr de forma correcta el proyecto. Haciendo esto solucionas los problemas de compatibilidad y dependencias.
