### ISSUE TITLE
nodeV18环境下npm install报错

### ISSUE THREAD

**Issue by doupengfei** [PanJiaChen/vue-element-admin#4047]
node升级到18的版本，项目重新install时，提示vs版本过低，安装了vs2019还是报错，有啥好的解决办法吗？难道只能降node版本吗？
`5769 error gyp ERR! find VS **************************************************************
5769 error gyp ERR! find VS 
5769 error gyp ERR! configure error 
5769 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
5769 error gyp ERR! stack     at VisualStudioFinder.fail (D:\soft\node\node-v18.7.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
5769 error gyp ERR! stack     at D:\soft\node\node-v18.7.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
5769 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\soft\node\node-v18.7.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
5769 error gyp ERR! stack     at D:\soft\node\node-v18.7.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
5769 error gyp ERR! stack     at D:\soft\node\node-v18.7.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
5769 error gyp ERR! stack     at D:\soft\node\node-v18.7.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
5769 error gyp ERR! stack     at D:\soft\node\node-v18.7.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
5769 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:418:5)
5769 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
5769 error gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
5769 error gyp ERR! System Windows_NT 10.0.18363
5769 error gyp ERR! command "D:\\soft\\node\\node-v18.7.0-win-x64\\node.exe" "D:\\soft\\node\\node-v18.7.0-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
5769 error gyp ERR! cwd D:\work-idea\frontend\rcontrol-vue-lf\node_modules\deasync
5769 error gyp ERR! node -v v18.7.0
5769 error gyp ERR! node-gyp -v v9.0.0
5769 error gyp ERR! not ok 
5769 error Build failed`

**Comment by pzting** [comment]
降级也不行，我node16可以，14就不行。也不知道咋回事

**Comment by Jan-xao** [comment]
> 降级也行，我知道16可以，14就不行。
我16.15.0也不可以

**Comment by doupengfei** [comment]
网上搜的，好像也没啥其他的好办法

发自我的iPhone

**Comment by No2015** [comment]
https://www.panziye.com/java/web/4794.html

**Comment by q552412** [comment]
把package-lock.json这个文件删除 node_modules删除重新npm （别删错把package.json删了）
