### ISSUE TITLE
克隆项目后无法成功安装依赖Operation timed out，网络可以正常google

### ISSUE THREAD

**Issue by fantasy525** [PanJiaChen/vue-element-admin#4084]
#### Steps to reproduce（问题复现步骤）

1. 克隆项目到本地电脑
2. yarn
3. 有网络超时的报错出现
4. ` fatal: unable to access 'https://github.com/nhn/raphael.git/': LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60
    at ProcessTermError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/local/lib/node_modules/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:25787:17)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) `

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/22516157/196594175-2a1888c0-f69a-468b-98d5-798143fa41be.png)

#### Other relevant information（格外信息）
- Your OS: MacOS Monterey 12.5.1
- Node.js version: 16.17.1
- vue-element-admin version: 4.4.0

**Comment by fantasy525** [comment]
#4063 #4049

**Comment by fantasy525** [comment]
看到一篇文章给出了解决方案，是 项目依赖的 tui-editor 插件包更换了包名，导致无法正常安装成功，一直卡在这里，因此解决办法很简单，更换项目package.json里面  tui-editor 为@toast-ui/editor 即可，同时也希望作者能进行更改
![image](https://user-images.githubusercontent.com/22516157/196595062-4d96605b-821a-4e86-944b-b7382eba6e57.png)
