### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by tiger8888** [PanJiaChen/vue-element-admin#499]
环境: 
nodeJs: v4.8.7
 npm:3.5.3

运行npm run dev时报如下错误:
 ERROR  Failed to compile with 3 errors                                 17:37:26

 error  in ./src/App.vue

Syntax Error: Unexpected token {

 @ ./src/main.js 11:0-24
 @ multi (webpack)-dev-server/client?http://localhost:9528 webpack/hot/dev-server ./src/main.js

 error  in ./src/views/layout/Layout.vue

Syntax Error: Unexpected token {

 @ ./src/router/index.js 10:0-44
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9528 webpack/hot/dev-server ./src/main.js

 error  in ./src/components/SvgIcon/index.vue

Syntax Error: Unexpected token {

 @ ./src/icons/index.js 2:0-43
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9528 webpack/hot/dev-server ./src/main.js

URIError: Failed to decode param '/%3C%='
    at decodeURIComponent (native)
    at decode_param (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/index.js:317:13)
    at /Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/index.js:317:13)
    at /Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/taivex2/Desktop/未命名文件夹/vue-element-admin-master/node_modules/express/lib/router/index.js:335:12)

**Comment by gagayang** [comment]
我也遇到这个问题了，哥们你咋解决的。
