### ISSUE TITLE
有问题请看这里！

### ISSUE THREAD

**Issue by PanJiaChen** [PanJiaChen/vue-element-admin#58]
遇到问题首先在issue里面找找有没有类似的问题
如果没有再去wiki或者在之前的系类文章中有没有介绍
在没有你可以自己提一个issue或者加入qq群：591724180进行提问

**Comment by tonymiao2012** [comment]
上面的wiki链接404

**Comment by PanJiaChen** [comment]
@tonymiao2012 谢谢提醒 已修复

**Comment by FE-Hns** [comment]
想知道，node-sass为什么总是安装不是，尝试了各种方式，求一点小指导

**Comment by PanJiaChen** [comment]
@FE-Hns wiki里都给了方案

**Comment by Twitchboy** [comment]
可以 聊聊这个 后台Store 的实现方式是怎样的设计？

**Comment by lecykx** [comment]
您好，这IE下报错提示SCRIPT1003: 缺少 ':' ，完全打不开，有没有解决的方法

**Comment by PanJiaChen** [comment]
@lecykx 请单独开issue 并提供更详细信息，过一会改评论会删除，请及时更新

**Comment by shihua-guo** [comment]
你好！群满员了。

**Comment by onlymisaky** [comment]
这个项目比那个vue2-elm好的太多太多了

**Comment by gtyang** [comment]
从 git pull 新版本后，执行 npm run dev，报错：

> vue-element-admin@3.1.1 dev /Users/apple/projects/vue-element-admin
> node build/dev-server.js

module.js:538
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/apple/projects/vue-element-admin/build/dev-server.js:10:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by PanJiaChen** [comment]
谢谢支持

**Comment by mysteryHJJ** [comment]
想问一下，1.x版本升级，侧边导航变成一半白半黑 了

**Comment by a13514097** [comment]
多标签间切换有时能保存之前的数据有时不行

**Comment by Eugene-Armstrong** [comment]
导出excel时怎样才可以导出多个sheets？

**Comment by femaimi9527** [comment]
> 这个项目比那个vue2-elm好的太多太多了

说说理由呗
