### ISSUE TITLE
build:sit之后 IE下页面加载不出   控制台报错,其他浏览器正常

### ISSUE THREAD

**Issue by DaneilDeng** [PanJiaChen/vue-element-admin#627]
"ReferenceError: “Promise”未定义
at o (http://localhost:8015/static/js/app.0b27bb9f6e11d4cbfc60.js:1:60352)
 at Anonymous function (http://localhost:8015/static/js/app.0b27bb9f6e11d4cbfc60.js:1:21743)

**Comment by DaneilDeng** [comment]
奇怪的是用edge模拟IE又没有问题

**Comment by DaneilDeng** [comment]
自己解决了    引用了babel-polyfill就可以了
