### ISSUE TITLE
执行 : npm run build:sit报错。

### ISSUE THREAD

**Issue by yangchaojiang** [PanJiaChen/vue-element-admin#684]
npm ERR! missing script: build:sit

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yangc\AppData\Roaming\npm-cache\_logs\2018-05-21T08_29_41_648Z-debug.log

**Comment by PanJiaChen** [comment]
请提供详细信息。

**Comment by yangchaojiang** [comment]
E:\project\fund-admin>npm run build:prod --preview
npm ERR! missing script: build:prod

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yangc\AppData\Roaming\npm-cache\_logs\2018-05-21T08_34_20_395Z-debug.log

日志文件
```
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:prod',
1 verbose cli   '--preview' ]
2 info using npm@5.6.0
3 info using node@v9.9.0
4 verbose stack Error: missing script: build:prod
4 verbose stack     at run (F:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at F:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at F:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at F:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (F:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (F:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (F:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at F:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:348:12
4 verbose stack     at F:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
5 verbose cwd E:\project\fund-admin
6 verbose Windows_NT 10.0.17134
7 verbose argv "F:\\Program Files\\nodejs\\node.exe" "F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod" "--preview"
8 verbose node v9.9.0
9 verbose npm  v5.6.0
10 error missing script: build:prod
11 verbose exit [ 1, true ]

```

**Comment by PanJiaChen** [comment]
看一下你的`package.json` 文件里面有没有这个`script`
https://github.com/PanJiaChen/vue-element-admin/blob/66613f0373c7fb5e5673a2890b1b435c061a4b04/package.json#L9

**Comment by yangchaojiang** [comment]
没有尼
![image](https://user-images.githubusercontent.com/13806413/40300128-ebd74be4-5d1a-11e8-8e6f-1a832f22da0f.png)

**Comment by yangchaojiang** [comment]
加上就行了吗

**Comment by PanJiaChen** [comment]
请自行研究npm script 是干嘛的。
