### ISSUE TITLE
修改config/index.js里面的assetsPublicPath参数后，无法显示

### ISSUE THREAD

**Issue by gateslu** [PanJiaChen/vue-element-admin#698]
在npm run dev操作下：
因为静态资源路径需要修改，添加前缀，所以就对dev的assetsPublicPath进行修改，
assetsPublicPath:"/"
修改成：
assetsPublicPath:"/test/"
然后整个vue页面都显示不了了

以上操作在build下对进行相同的修改，但是打包之后运行没问题，目前无法使用dev进行调试

**Comment by gateslu** [comment]
我是修改了dev下面的【assetsPublicPath: '/',】，比如在模板的基础上将'/'修改成'/test/'，在执行 npm run dev的时候就会报错，页面也无法打开，因为我直接用vue的webpack模板的话，修改这个值是没问题的，所有我也尝试修改这个值
 10% building modules 5/7 modules 2 active ...app\src\vue-element-admin\src\main.jsURIError: Failed to decode param '/%3C%='
    at decodeURIComponent (<anonymous>)
    at decode_param (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\layer.js:172:12)
    at Layer.match (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\layer.js:123:27)
    at matchLayer (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\index.js:574:18)
    at next (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\index.js:220:15)
    at expressInit (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\index.js:317:13)
    at M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\index.js:335:12)
    at next (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\index.js:275:10)
    at query (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\index.js:317:13)
    at M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (M:\GOPATH\src\VoiceCloud\webapp\src\vue-element-admin\node_modules\express\lib\router\in 95% emitting

**Comment by PanJiaChen** [comment]
首先我觉得没什么必要修改`dev`的`assetsPublicPath`
你可以看看这个[issue](https://github.com/vuejs-templates/webpack/issues/1176)

**Comment by gateslu** [comment]
好的，我看看，谢谢！
