### ISSUE TITLE
Unable to run dev

### ISSUE THREAD

**Issue by Festum** [PanJiaChen/vue-element-admin#956]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.2.0
3 info using node@v10.7.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-element-admin@3.7.3~predev: vue-element-admin@3.7.3
6 info lifecycle vue-element-admin@3.7.3~dev: vue-element-admin@3.7.3
7 verbose lifecycle vue-element-admin@3.7.3~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-element-admin@3.7.3~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/festum/Repo/domain-admin/node_modules/.bin:/Users/festum/Repo/framework/venv/bin:/usr/bin/:/usr/local/bin:/usr/local/share/npm/bin:/Users/festum/bin:/Users/festum/local/node/bin:/usr/local/go/bin:/Users/festum/Library/Python/3.6/bin:/Users/festum/Library/Python/2.7/bin:/Users/festum/.local/bin:/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/:/Users/festum/.gvm/pkgsets/go1.10.3/global/bin:/Users/festum/.gvm/gos/go1.10.3/bin:/Users/festum/.gvm/pkgsets/go1.10.3/global/overlay/bin:/Users/festum/.gvm/bin:/Users/festum/.gvm/bin:/Users/festum/.nvm/versions/node/v10.6.0/bin:/usr/bin/:/usr/local/bin:/usr/local/share/npm/bin:/Users/festum/bin:/Users/festum/local/node/bin:/usr/local/go/bin:/Users/festum/Library/Python/3.6/bin:/Users/festum/Library/Python/2.7/bin:/Users/festum/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/festum/.gvm/pkgsets/go1.10.3/global/bin:/Users/festum/.gvm/gos/go1.10.3/bin:/Users/festum/.gvm/pkgsets/go1.10.3/global/overlay/bin:/Users/festum/.gvm/bin:/usr/bin/:/usr/local/share/npm/bin:/Users/festum/bin:/Users/festum/local/node/bin:/usr/local/go/bin:/Users/festum/Library/Python/3.6/bin:/Users/festum/Library/Python/2.7/bin:/Users/festum/.local/bin
9 verbose lifecycle vue-element-admin@3.7.3~dev: CWD: /Users/festum/Repo/domain-admin
10 silly lifecycle vue-element-admin@3.7.3~dev: Args: [ '-c',
10 silly lifecycle   'cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js' ]
11 silly lifecycle vue-element-admin@3.7.3~dev: Returned: code: 1  signal: null
12 info lifecycle vue-element-admin@3.7.3~dev: Failed to exec dev script
13 verbose stack Error: vue-element-admin@3.7.3 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid vue-element-admin@3.7.3
15 verbose cwd /Users/festum/Repo/domain-admin
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/10.7.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v10.7.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-element-admin@3.7.3 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
22 error Exit status 1
23 error Failed at the vue-element-admin@3.7.3 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by PanJiaChen** [comment]
```bash
npm cache clean --force

npm install

npm run dev
```

**Comment by Festum** [comment]
```
(master {1} ✓) domain-admin npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
(master {1} ✓) domain-admin npm install
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

audited 11967 packages in 8.839s
found 0 vulnerabilities

(master {1} ✓) domain-admin npm run dev

> vue-element-admin@3.7.3 dev /Users/festum/Repo/domain-admin
> cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 10% building modules 1/1 modules 0 activeevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 192.168.99.100:9527
    at Server.setupListenHandle [as _listen2] (net.js:1319:19)
    at listenInCluster (net.js:1384:12)
    at doListen (net.js:1510:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1363:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@3.7.3 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-element-admin@3.7.3 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/festum/.npm/_logs/2018-08-14T14_16_04_026Z-debug.log

```

```
(master {1} ✓) domain-admin cat /Users/festum/.npm/_logs/2018-08-14T14_16_04_026Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.3.0
3 info using node@v10.7.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-element-admin@3.7.3~predev: vue-element-admin@3.7.3
6 info lifecycle vue-element-admin@3.7.3~dev: vue-element-admin@3.7.3
7 verbose lifecycle vue-element-admin@3.7.3~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-element-admin@3.7.3~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/festum/Repo/domain-admin/node_modules/.bin:/Users/festum/Repo/framework/venv/bin:/usr/bin/:/usr/local/bin:/usr/local/share/npm/bin:/Users/festum/bin:/Users/festum/local/node/bin:/usr/local/go/bin:/Users/festum/Library/Python/3.6/bin:/Users/festum/Library/Python/2.7/bin:/Users/festum/.local/bin:/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/:/Users/festum/.gvm/pkgsets/go1.10.3/global/bin:/Users/festum/.gvm/gos/go1.10.3/bin:/Users/festum/.gvm/pkgsets/go1.10.3/global/overlay/bin:/Users/festum/.gvm/bin:/Users/festum/.gvm/bin:/Users/festum/.nvm/versions/node/v10.6.0/bin:/usr/bin/:/usr/local/bin:/usr/local/share/npm/bin:/Users/festum/bin:/Users/festum/local/node/bin:/usr/local/go/bin:/Users/festum/Library/Python/3.6/bin:/Users/festum/Library/Python/2.7/bin:/Users/festum/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/festum/.gvm/pkgsets/go1.10.3/global/bin:/Users/festum/.gvm/gos/go1.10.3/bin:/Users/festum/.gvm/pkgsets/go1.10.3/global/overlay/bin:/Users/festum/.gvm/bin:/usr/bin/:/usr/local/share/npm/bin:/Users/festum/bin:/Users/festum/local/node/bin:/usr/local/go/bin:/Users/festum/Library/Python/3.6/bin:/Users/festum/Library/Python/2.7/bin:/Users/festum/.local/bin
9 verbose lifecycle vue-element-admin@3.7.3~dev: CWD: /Users/festum/Repo/domain-admin
10 silly lifecycle vue-element-admin@3.7.3~dev: Args: [ '-c',
10 silly lifecycle   'cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js' ]
11 silly lifecycle vue-element-admin@3.7.3~dev: Returned: code: 1  signal: null
12 info lifecycle vue-element-admin@3.7.3~dev: Failed to exec dev script
13 verbose stack Error: vue-element-admin@3.7.3 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid vue-element-admin@3.7.3
15 verbose cwd /Users/festum/Repo/domain-admin
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/10.7.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v10.7.0
19 verbose npm  v6.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-element-admin@3.7.3 dev: `cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
22 error Exit status 1
23 error Failed at the vue-element-admin@3.7.3 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by PanJiaChen** [comment]
Please google `listen EADDRNOTAVAIL`.

**Comment by PanJiaChen** [comment]
And if you want dev by ip, please set host: '0.0.0.0'

https://github.com/PanJiaChen/vue-element-admin/blob/312a2ca8ed59975e3658e5ce47c9761fa1947c34/config/index.js#L17-L19
